---
title: mlr-2.14.0
authors: ["Patrick Schratz"]
date: '2019-04-18'
slug: mlr-2-14-0
categories:
  - r-bloggers
tags:
  - release
description: "The new mlr-2.14.0 and announcement of mlr3"

---

The last _mlr_ release was in August 2018 - so it was definitely time for a new release after around 9 months of development!

The NEWS file can be found directly [here](https://mlr.mlr-org.com/news/index.html).

In this post we highlight some of the new implementations that come along with this release of v2.14.0

## Filters

We integrated the filter methods from the _praznik_ package. These were quite few:

- praznik_JMI
- praznik_DISR
- praznik_JMIM
- praznik_MIM
- praznik_NJMIM
- praznik_MRMR
- praznik_CMIM

Also, a long awaited PR that we finally merged was the inclusion of the _FSelectorRcpp_ filters.
These are around 100 times faster than the Java-driven ones from the _FSelector_ package.

In addition, we are now using a consistent naming scheme for the filters following `<package-name>_<filter-name>`.
This change might break your existing code if you used _mlr_ filters before.
However, since it is just a naming change we think the burden of updating your code is acceptable.

## Learners

Two new learners were added:

- classif.liquidSVM
- regr.liquidSVM

Learner `regr.h2o.gbm` now uses `h2o.use.data.table = TRUE` by default which should result in a runtime performance increase.

It is also possible to retrieve the feature importance of h2O learners now.

## Resampling

You can now provide fully predefined indices for resampling.
This is useful for datasets that have a certain grouping structure (e.g. spatial data) that is difficult to specify otherwise.

## mlr-org NEWS

You might be wondering what we've been up to in the last months in our group.
The major project that we started was [mlr3](https://github.com/mlr-org/mlr3).
This is a clean rewrite of _mlr_ with a modular structure to simplify usage and maintenance of the "mlr idea" in the future, both for users and developers.
We are not completely finished yet, but you can take a look at the Github repo at what we have achieved so far.
Once we are ready to release the initial version, we will of course write a dedicated post about it.

Putting a lot of time into _mlr3_ means having less time for responding to issues and questions in _mlr_.
We would like to apologize for this.
We are working on this more or less as a side project along our day jobs and our resources are limited.
If you want to help and get involved with _mlr_ or _mlr3_, we would be very happy to have you.
Our team is not a closed group and anyone can contribute to the mlr-org projects.

The change in development focus also led to a change of maintainer for _mlr_.
As [Bernd Bischl](https://www.compstat.statistik.uni-muenchen.de/people/bischl/) (the creator and maintainer) of _mlr_ has a lot of duties, we decided to make [Lars Kotthoff](https://www.cs.uwyo.edu/~larsko/) and [Patrick Schratz](https://pjs-web.de/) the new maintainers of the _mlr_ package.

_mlr_ will only get bug fixes and minor updates, as we are focusing the development of new things on _mlr3_.
Right now, we have over 400 issues and 30 pull requests so there is a still a lot to do :)

## Roadmap for mlr

We are will publish new releases every three months from now on, regardless of the changes that have come in.
_mlr_ will continue to exist next to _mlr3_.
If users start contributing new features to _mlr_, we are also happy to include those in the package.
As announced already, we will clean up the _mlr_ repo issue and pull request in the coming months to be able to fully concentrate on _mlr3_ after its initial release.
