{
  "hash": "ddb6138b2f05ad9cb120f2d9cc1d311f",
  "result": {
    "markdown": "---\ntitle: mlr3 and OpenML - Moneyball Use Case\ncategories:\n  - imputation\n  - regression\n  - feature importance\n  - mlr3pipelines\nauthor:\n  - name: Philipp Kopper\ndate: 05-04-2020\ndescription: |\n  Download data from OpenML data and impute missing values.\nimage: thumbnail.png\n---\n\n\n\n\nThis use case shows how to easily work with datasets available via [OpenML](https://www.openml.org/) into an [mlr3](https://mlr3.mlr-org.com) workflow.\n\nThe following operations are illustrated:\n\n* Creating tasks and learners\n* Imputation for missing values\n* Training and predicting\n* Resampling / Cross-validation\n\n## Prerequisites\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# various functions of the mlr3 ecosystem\nlibrary(\"mlr3verse\")\n# about a dozen reasonable learners\nlibrary(\"mlr3learners\")\n# retrieving the data\nlibrary(\"OpenML\")\n```\n:::\n\n\nWe initialize the random number generator with a fixed seed for reproducibility, and decrease the verbosity of the logger to keep the output clearly represented.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(7832)\nlgr::get_logger(\"mlr3\")$set_threshold(\"warn\")\n```\n:::\n\n\n## Retrieving the data from OpenML\n\nWe can use the [OpenML](https://cran.r-project.org/package=OpenML) package to retrieve data (and more) straight away.\n[OpenML](https://cran.r-project.org/package=OpenML) is is an inclusive movement to build an open, organized, online ecosystem for machine learning.\nTypically, you can retrieve the data with an `data.id`.\nThe id can be found on [OpenML](https://www.openml.org/).\nWe choose the data set `41021`.\nThe related web page can be accessed [here](https://www.openml.org/d/41021).\nThis data set was uploaded by [Joaquin Vanschoren](https://www.openml.org/u/2).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noml_data = getOMLDataSet(data.id = 41021)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDownloading from 'http://www.openml.org/api/v1/data/41021' to '/tmp/RtmpGIloTm/cache/datasets/41021/description.xml'.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nDownloading from 'https://api.openml.org/data/v1/download/18626236/Moneyball.arff' to '/tmp/RtmpGIloTm/cache/datasets/41021/dataset.arff'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: readr\n```\n:::\n:::\n\n\nThe description indicates that the data set is associated with baseball or more precisely the story of [Moneyball](https://www.imdb.com/title/tt1210166/).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(as.data.table(oml_data))\n```\n:::\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-383b1f5e2ddb09965548\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-383b1f5e2ddb09965548\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\",\"180\",\"181\",\"182\",\"183\",\"184\",\"185\",\"186\",\"187\",\"188\",\"189\",\"190\",\"191\",\"192\",\"193\",\"194\",\"195\",\"196\",\"197\",\"198\",\"199\",\"200\",\"201\",\"202\",\"203\",\"204\",\"205\",\"206\",\"207\",\"208\",\"209\",\"210\",\"211\",\"212\",\"213\",\"214\",\"215\",\"216\",\"217\",\"218\",\"219\",\"220\",\"221\",\"222\",\"223\",\"224\",\"225\",\"226\",\"227\",\"228\",\"229\",\"230\",\"231\",\"232\",\"233\",\"234\",\"235\",\"236\",\"237\",\"238\",\"239\",\"240\",\"241\",\"242\",\"243\",\"244\",\"245\",\"246\",\"247\",\"248\",\"249\",\"250\",\"251\",\"252\",\"253\",\"254\",\"255\",\"256\",\"257\",\"258\",\"259\",\"260\",\"261\",\"262\",\"263\",\"264\",\"265\",\"266\",\"267\",\"268\",\"269\",\"270\",\"271\",\"272\",\"273\",\"274\",\"275\",\"276\",\"277\",\"278\",\"279\",\"280\",\"281\",\"282\",\"283\",\"284\",\"285\",\"286\",\"287\",\"288\",\"289\",\"290\",\"291\",\"292\",\"293\",\"294\",\"295\",\"296\",\"297\",\"298\",\"299\",\"300\",\"301\",\"302\",\"303\",\"304\",\"305\",\"306\",\"307\",\"308\",\"309\",\"310\",\"311\",\"312\",\"313\",\"314\",\"315\",\"316\",\"317\",\"318\",\"319\",\"320\",\"321\",\"322\",\"323\",\"324\",\"325\",\"326\",\"327\",\"328\",\"329\",\"330\",\"331\",\"332\",\"333\",\"334\",\"335\",\"336\",\"337\",\"338\",\"339\",\"340\",\"341\",\"342\",\"343\",\"344\",\"345\",\"346\",\"347\",\"348\",\"349\",\"350\",\"351\",\"352\",\"353\",\"354\",\"355\",\"356\",\"357\",\"358\",\"359\",\"360\",\"361\",\"362\",\"363\",\"364\",\"365\",\"366\",\"367\",\"368\",\"369\",\"370\",\"371\",\"372\",\"373\",\"374\",\"375\",\"376\",\"377\",\"378\",\"379\",\"380\",\"381\",\"382\",\"383\",\"384\",\"385\",\"386\",\"387\",\"388\",\"389\",\"390\",\"391\",\"392\",\"393\",\"394\",\"395\",\"396\",\"397\",\"398\",\"399\",\"400\",\"401\",\"402\",\"403\",\"404\",\"405\",\"406\",\"407\",\"408\",\"409\",\"410\",\"411\",\"412\",\"413\",\"414\",\"415\",\"416\",\"417\",\"418\",\"419\",\"420\",\"421\",\"422\",\"423\",\"424\",\"425\",\"426\",\"427\",\"428\",\"429\",\"430\",\"431\",\"432\",\"433\",\"434\",\"435\",\"436\",\"437\",\"438\",\"439\",\"440\",\"441\",\"442\",\"443\",\"444\",\"445\",\"446\",\"447\",\"448\",\"449\",\"450\",\"451\",\"452\",\"453\",\"454\",\"455\",\"456\",\"457\",\"458\",\"459\",\"460\",\"461\",\"462\",\"463\",\"464\",\"465\",\"466\",\"467\",\"468\",\"469\",\"470\",\"471\",\"472\",\"473\",\"474\",\"475\",\"476\",\"477\",\"478\",\"479\",\"480\",\"481\",\"482\",\"483\",\"484\",\"485\",\"486\",\"487\",\"488\",\"489\",\"490\",\"491\",\"492\",\"493\",\"494\",\"495\",\"496\",\"497\",\"498\",\"499\",\"500\",\"501\",\"502\",\"503\",\"504\",\"505\",\"506\",\"507\",\"508\",\"509\",\"510\",\"511\",\"512\",\"513\",\"514\",\"515\",\"516\",\"517\",\"518\",\"519\",\"520\",\"521\",\"522\",\"523\",\"524\",\"525\",\"526\",\"527\",\"528\",\"529\",\"530\",\"531\",\"532\",\"533\",\"534\",\"535\",\"536\",\"537\",\"538\",\"539\",\"540\",\"541\",\"542\",\"543\",\"544\",\"545\",\"546\",\"547\",\"548\",\"549\",\"550\",\"551\",\"552\",\"553\",\"554\",\"555\",\"556\",\"557\",\"558\",\"559\",\"560\",\"561\",\"562\",\"563\",\"564\",\"565\",\"566\",\"567\",\"568\",\"569\",\"570\",\"571\",\"572\",\"573\",\"574\",\"575\",\"576\",\"577\",\"578\",\"579\",\"580\",\"581\",\"582\",\"583\",\"584\",\"585\",\"586\",\"587\",\"588\",\"589\",\"590\",\"591\",\"592\",\"593\",\"594\",\"595\",\"596\",\"597\",\"598\",\"599\",\"600\",\"601\",\"602\",\"603\",\"604\",\"605\",\"606\",\"607\",\"608\",\"609\",\"610\",\"611\",\"612\",\"613\",\"614\",\"615\",\"616\",\"617\",\"618\",\"619\",\"620\",\"621\",\"622\",\"623\",\"624\",\"625\",\"626\",\"627\",\"628\",\"629\",\"630\",\"631\",\"632\",\"633\",\"634\",\"635\",\"636\",\"637\",\"638\",\"639\",\"640\",\"641\",\"642\",\"643\",\"644\",\"645\",\"646\",\"647\",\"648\",\"649\",\"650\",\"651\",\"652\",\"653\",\"654\",\"655\",\"656\",\"657\",\"658\",\"659\",\"660\",\"661\",\"662\",\"663\",\"664\",\"665\",\"666\",\"667\",\"668\",\"669\",\"670\",\"671\",\"672\",\"673\",\"674\",\"675\",\"676\",\"677\",\"678\",\"679\",\"680\",\"681\",\"682\",\"683\",\"684\",\"685\",\"686\",\"687\",\"688\",\"689\",\"690\",\"691\",\"692\",\"693\",\"694\",\"695\",\"696\",\"697\",\"698\",\"699\",\"700\",\"701\",\"702\",\"703\",\"704\",\"705\",\"706\",\"707\",\"708\",\"709\",\"710\",\"711\",\"712\",\"713\",\"714\",\"715\",\"716\",\"717\",\"718\",\"719\",\"720\",\"721\",\"722\",\"723\",\"724\",\"725\",\"726\",\"727\",\"728\",\"729\",\"730\",\"731\",\"732\",\"733\",\"734\",\"735\",\"736\",\"737\",\"738\",\"739\",\"740\",\"741\",\"742\",\"743\",\"744\",\"745\",\"746\",\"747\",\"748\",\"749\",\"750\",\"751\",\"752\",\"753\",\"754\",\"755\",\"756\",\"757\",\"758\",\"759\",\"760\",\"761\",\"762\",\"763\",\"764\",\"765\",\"766\",\"767\",\"768\",\"769\",\"770\",\"771\",\"772\",\"773\",\"774\",\"775\",\"776\",\"777\",\"778\",\"779\",\"780\",\"781\",\"782\",\"783\",\"784\",\"785\",\"786\",\"787\",\"788\",\"789\",\"790\",\"791\",\"792\",\"793\",\"794\",\"795\",\"796\",\"797\",\"798\",\"799\",\"800\",\"801\",\"802\",\"803\",\"804\",\"805\",\"806\",\"807\",\"808\",\"809\",\"810\",\"811\",\"812\",\"813\",\"814\",\"815\",\"816\",\"817\",\"818\",\"819\",\"820\",\"821\",\"822\",\"823\",\"824\",\"825\",\"826\",\"827\",\"828\",\"829\",\"830\",\"831\",\"832\",\"833\",\"834\",\"835\",\"836\",\"837\",\"838\",\"839\",\"840\",\"841\",\"842\",\"843\",\"844\",\"845\",\"846\",\"847\",\"848\",\"849\",\"850\",\"851\",\"852\",\"853\",\"854\",\"855\",\"856\",\"857\",\"858\",\"859\",\"860\",\"861\",\"862\",\"863\",\"864\",\"865\",\"866\",\"867\",\"868\",\"869\",\"870\",\"871\",\"872\",\"873\",\"874\",\"875\",\"876\",\"877\",\"878\",\"879\",\"880\",\"881\",\"882\",\"883\",\"884\",\"885\",\"886\",\"887\",\"888\",\"889\",\"890\",\"891\",\"892\",\"893\",\"894\",\"895\",\"896\",\"897\",\"898\",\"899\",\"900\",\"901\",\"902\",\"903\",\"904\",\"905\",\"906\",\"907\",\"908\",\"909\",\"910\",\"911\",\"912\",\"913\",\"914\",\"915\",\"916\",\"917\",\"918\",\"919\",\"920\",\"921\",\"922\",\"923\",\"924\",\"925\",\"926\",\"927\",\"928\",\"929\",\"930\",\"931\",\"932\",\"933\",\"934\",\"935\",\"936\",\"937\",\"938\",\"939\",\"940\",\"941\",\"942\",\"943\",\"944\",\"945\",\"946\",\"947\",\"948\",\"949\",\"950\",\"951\",\"952\",\"953\",\"954\",\"955\",\"956\",\"957\",\"958\",\"959\",\"960\",\"961\",\"962\",\"963\",\"964\",\"965\",\"966\",\"967\",\"968\",\"969\",\"970\",\"971\",\"972\",\"973\",\"974\",\"975\",\"976\",\"977\",\"978\",\"979\",\"980\",\"981\",\"982\",\"983\",\"984\",\"985\",\"986\",\"987\",\"988\",\"989\",\"990\",\"991\",\"992\",\"993\",\"994\",\"995\",\"996\",\"997\",\"998\",\"999\",\"1000\",\"1001\",\"1002\",\"1003\",\"1004\",\"1005\",\"1006\",\"1007\",\"1008\",\"1009\",\"1010\",\"1011\",\"1012\",\"1013\",\"1014\",\"1015\",\"1016\",\"1017\",\"1018\",\"1019\",\"1020\",\"1021\",\"1022\",\"1023\",\"1024\",\"1025\",\"1026\",\"1027\",\"1028\",\"1029\",\"1030\",\"1031\",\"1032\",\"1033\",\"1034\",\"1035\",\"1036\",\"1037\",\"1038\",\"1039\",\"1040\",\"1041\",\"1042\",\"1043\",\"1044\",\"1045\",\"1046\",\"1047\",\"1048\",\"1049\",\"1050\",\"1051\",\"1052\",\"1053\",\"1054\",\"1055\",\"1056\",\"1057\",\"1058\",\"1059\",\"1060\",\"1061\",\"1062\",\"1063\",\"1064\",\"1065\",\"1066\",\"1067\",\"1068\",\"1069\",\"1070\",\"1071\",\"1072\",\"1073\",\"1074\",\"1075\",\"1076\",\"1077\",\"1078\",\"1079\",\"1080\",\"1081\",\"1082\",\"1083\",\"1084\",\"1085\",\"1086\",\"1087\",\"1088\",\"1089\",\"1090\",\"1091\",\"1092\",\"1093\",\"1094\",\"1095\",\"1096\",\"1097\",\"1098\",\"1099\",\"1100\",\"1101\",\"1102\",\"1103\",\"1104\",\"1105\",\"1106\",\"1107\",\"1108\",\"1109\",\"1110\",\"1111\",\"1112\",\"1113\",\"1114\",\"1115\",\"1116\",\"1117\",\"1118\",\"1119\",\"1120\",\"1121\",\"1122\",\"1123\",\"1124\",\"1125\",\"1126\",\"1127\",\"1128\",\"1129\",\"1130\",\"1131\",\"1132\",\"1133\",\"1134\",\"1135\",\"1136\",\"1137\",\"1138\",\"1139\",\"1140\",\"1141\",\"1142\",\"1143\",\"1144\",\"1145\",\"1146\",\"1147\",\"1148\",\"1149\",\"1150\",\"1151\",\"1152\",\"1153\",\"1154\",\"1155\",\"1156\",\"1157\",\"1158\",\"1159\",\"1160\",\"1161\",\"1162\",\"1163\",\"1164\",\"1165\",\"1166\",\"1167\",\"1168\",\"1169\",\"1170\",\"1171\",\"1172\",\"1173\",\"1174\",\"1175\",\"1176\",\"1177\",\"1178\",\"1179\",\"1180\",\"1181\",\"1182\",\"1183\",\"1184\",\"1185\",\"1186\",\"1187\",\"1188\",\"1189\",\"1190\",\"1191\",\"1192\",\"1193\",\"1194\",\"1195\",\"1196\",\"1197\",\"1198\",\"1199\",\"1200\",\"1201\",\"1202\",\"1203\",\"1204\",\"1205\",\"1206\",\"1207\",\"1208\",\"1209\",\"1210\",\"1211\",\"1212\",\"1213\",\"1214\",\"1215\",\"1216\",\"1217\",\"1218\",\"1219\",\"1220\",\"1221\",\"1222\",\"1223\",\"1224\",\"1225\",\"1226\",\"1227\",\"1228\",\"1229\",\"1230\",\"1231\",\"1232\"],[\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIA\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBR\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBR\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBR\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBR\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBR\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"WSN\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAA\",\"LAD\",\"MIL\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"WSN\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ARI\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TBD\",\"TEX\",\"TOR\",\"ANA\",\"ATL\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"COL\",\"DET\",\"FLA\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEA\",\"SFG\",\"STL\",\"TEX\",\"TOR\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"TEX\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"TEX\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"TEX\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"TEX\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"WSA\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIL\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SFG\",\"STL\",\"WSA\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCR\",\"LAD\",\"MIN\",\"MON\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SDP\",\"SEP\",\"SFG\",\"STL\",\"WSA\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"LAD\",\"MIN\",\"NYM\",\"NYY\",\"OAK\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAD\",\"MIN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"ATL\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAD\",\"MIN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"BAL\",\"BOS\",\"CAL\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAD\",\"MIN\",\"MLN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAA\",\"LAD\",\"MIN\",\"MLN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAA\",\"LAD\",\"MIN\",\"MLN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\",\"BAL\",\"BOS\",\"CHC\",\"CHW\",\"CIN\",\"CLE\",\"DET\",\"HOU\",\"KCA\",\"LAA\",\"LAD\",\"MIN\",\"MLN\",\"NYM\",\"NYY\",\"PHI\",\"PIT\",\"SFG\",\"STL\",\"WSA\"],[\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"AL\",\"NL\",\"AL\",\"NL\",\"NL\",\"AL\",\"NL\",\"NL\",\"NL\",\"NL\",\"AL\"],[2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2011,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2009,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2007,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2005,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2004,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2003,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2002,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2001,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1999,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1998,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1997,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1996,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1993,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1992,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1991,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1990,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1989,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1988,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1987,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1986,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1985,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1978,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1976,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1975,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1974,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1973,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1971,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1970,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1969,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1968,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1967,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1966,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1965,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1964,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1963,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962,1962],[734,700,712,734,613,748,669,667,758,726,583,676,767,637,609,776,701,650,804,713,684,651,651,619,718,765,697,808,716,731,731,641,708,875,654,654,735,704,735,787,625,615,730,667,644,721,619,718,867,645,713,610,593,556,570,762,707,855,743,624,713,738,613,818,685,752,790,646,770,751,719,611,676,681,667,750,781,656,859,663,772,587,665,513,697,736,802,787,755,655,720,735,741,872,707,724,673,773,804,743,772,643,686,883,780,785,817,671,915,759,820,636,638,640,657,730,803,784,798,710,720,753,782,845,855,811,704,805,747,821,770,712,691,765,700,750,829,799,789,646,799,735,637,671,640,779,774,901,714,641,712,810,756,867,752,693,783,811,860,887,790,723,706,822,735,801,718,804,968,741,892,724,741,794,683,725,782,816,753,673,773,849,768,820,716,868,749,870,813,822,758,735,757,766,820,730,801,834,930,771,865,691,731,756,746,781,689,835,809,746,696,769,729,910,703,741,820,790,740,723,717,693,701,761,685,726,688,722,886,772,807,680,684,699,649,805,750,865,775,639,836,615,803,842,949,789,865,750,858,833,827,718,803,720,761,634,780,635,684,897,793,840,680,768,698,850,855,714,860,719,736,717,907,743,961,724,791,694,699,853,591,751,805,836,574,714,801,711,642,877,768,791,753,678,795,755,876,715,826,894,851,819,708,667,859,706,856,709,739,778,575,699,749,737,713,627,768,735,690,897,800,710,641,662,814,783,787,673,843,813,691,818,729,687,772,777,798,735,897,923,724,742,847,729,758,740,771,670,642,804,884,746,657,789,927,799,814,672,890,767,864,792,810,794,792,764,978,825,950,968,823,731,938,879,798,740,748,738,807,871,947,708,793,752,907,925,887,733,848,861,711,908,840,851,836,747,777,865,1009,906,747,691,823,856,793,815,686,718,853,900,893,841,775,710,859,872,809,772,945,883,787,665,826,817,876,831,861,750,850,826,722,667,874,714,669,707,734,644,706,965,804,713,650,749,859,845,810,620,940,816,829,791,812,851,687,779,651,868,923,784,740,777,747,742,681,772,691,777,891,764,668,725,795,925,784,689,807,654,773,949,928,762,772,898,778,952,961,783,688,753,746,703,894,877,741,746,871,861,650,776,771,993,752,759,928,766,767,786,686,684,738,776,722,790,758,899,581,716,675,675,733,693,732,672,821,715,877,707,679,734,808,758,835,847,682,705,599,579,593,738,660,674,791,608,610,548,740,747,648,599,733,745,686,693,617,679,574,631,682,780,749,686,731,653,695,758,689,576,817,605,727,665,799,776,579,640,674,760,629,768,636,702,649,651,829,684,682,669,699,690,690,682,693,732,750,573,707,728,732,666,662,775,603,733,646,733,673,640,719,599,676,767,584,708,774,669,702,693,632,604,617,647,690,554,707,740,632,683,698,712,629,637,642,694,699,632,695,731,555,550,813,714,660,631,641,666,703,617,704,628,682,759,628,703,772,800,597,651,594,664,670,578,637,763,747,729,842,770,720,748,783,742,896,648,715,635,862,786,741,823,788,806,702,723,668,760,783,798,823,845,615,708,794,786,680,644,732,831,798,654,654,638,667,741,637,783,797,731,739,663,656,718,698,601,771,809,632,818,800,732,686,736,677,729,729,706,687,682,690,705,633,695,839,757,667,568,650,719,556,747,617,759,632,681,810,696,762,679,627,761,829,693,673,580,641,673,593,652,758,738,720,615,686,682,682,652,656,750,746,799,724,722,701,800,623,704,789,643,696,654,764,709,677,575,770,708,696,659,653,558,687,679,639,795,739,774,753,814,676,786,545,683,729,569,784,691,891,657,697,609,709,691,664,724,675,651,673,685,590,651,630,805,757,698,614,587,707,738,830,637,809,663,811,670,694,611,820,686,728,666,591,610,573,738,756,624,669,757,841,866,706,730,731,760,770,583,851,739,807,764,701,593,734,573,683,775,603,711,672,731,750,613,600,659,796,691,664,634,710,639,714,605,743,727,804,666,633,607,735,532,708,684,591,614,613,600,692,590,678,719,859,675,692,844,802,676,714,680,822,769,639,867,665,587,831,605,847,734,692,624,673,737,767,605,620,619,716,550,611,586,857,615,609,625,713,608,570,743,531,615,730,686,770,708,570,595,629,616,583,682,796,628,712,655,840,688,570,664,710,648,675,724,601,646,681,758,735,712,552,659,662,714,661,659,696,618,669,684,776,662,620,653,667,798,647,673,662,572,671,689,676,751,541,634,677,690,799,754,738,629,614,652,741,680,642,681,755,675,708,738,668,608,641,758,642,704,548,739,643,619,643,742,691,511,637,617,586,543,701,585,603,663,534,654,622,588,648,691,558,788,486,706,739,537,736,792,786,631,806,633,775,649,666,744,611,749,613,744,687,695,680,678,594,729,681,831,744,626,691,779,743,528,720,625,798,573,701,676,586,645,790,582,632,562,740,645,725,468,639,713,595,694,514,579,614,498,612,463,690,516,671,510,470,562,473,536,569,543,583,599,583,524,631,654,722,567,702,531,604,559,683,626,533,519,671,498,522,612,679,652,695,550,782,755,655,604,644,574,692,574,719,612,564,606,663,587,611,696,759,675,571,557,641,669,527,635,647,825,663,680,569,585,608,774,708,495,611,654,675,682,707,591,679,688,649,642,660,689,699,495,621,544,614,737,803,569,730,693,663,656,715,578,644,666,570,683,648,635,700,464,615,597,640,767,677,501,714,642,567,725,747,578,652,707,632,707,802,682,758,592,745,718,842,798,730,617,817,705,706,878,774,599],[688,600,705,806,759,676,588,845,890,670,794,746,699,597,724,733,832,709,668,614,680,674,710,651,649,648,577,707,784,594,662,605,860,737,756,706,720,760,774,711,702,796,762,633,612,638,804,742,657,679,529,712,611,675,578,692,614,677,761,643,836,629,785,744,767,704,685,752,717,743,717,729,845,702,692,804,671,652,693,626,640,866,581,698,583,641,649,687,728,742,782,641,876,736,672,732,723,865,715,745,766,770,842,761,611,818,765,757,753,761,709,768,769,692,611,640,754,740,771,874,706,778,869,694,671,729,800,761,822,857,767,743,781,697,648,689,745,715,727,690,680,884,764,811,759,725,671,967,610,825,732,733,868,657,690,839,853,704,758,797,891,813,778,731,727,776,725,750,777,758,821,846,666,813,720,829,944,844,699,783,788,805,899,825,834,794,801,782,812,675,772,719,971,732,751,833,683,731,767,727,812,797,679,792,790,762,856,784,754,872,856,674,800,805,714,645,889,642,862,787,732,609,935,643,755,697,662,648,789,658,726,769,726,751,745,634,936,858,705,673,734,899,668,830,768,665,831,907,857,923,844,700,698,905,684,757,715,769,731,808,742,781,744,705,823,770,659,842,794,823,743,685,740,820,809,683,715,886,778,892,928,692,677,867,556,873,758,716,754,716,643,697,801,831,637,638,796,852,969,826,644,674,565,773,665,759,798,774,837,898,864,763,695,891,643,821,712,718,703,697,654,724,730,815,699,616,648,918,882,828,730,677,643,829,745,701,795,850,821,906,876,744,769,858,744,806,766,812,713,713,645,719,858,812,627,748,684,887,968,753,869,754,714,913,745,904,839,765,816,897,827,797,944,930,729,826,880,902,738,814,813,830,888,815,780,747,771,842,974,908,826,676,661,815,718,920,870,711,860,1028,882,852,675,921,787,886,845,853,711,731,846,846,782,781,905,831,838,913,859,862,783,812,581,785,729,792,931,760,779,855,863,923,620,899,678,812,818,783,645,656,866,808,718,635,855,739,782,751,871,768,794,581,681,857,759,833,764,815,908,790,669,660,820,645,742,861,740,709,688,946,840,760,891,833,793,708,823,694,648,903,921,943,771,794,773,769,964,1103,703,792,786,652,899,900,668,779,787,900,790,833,682,895,862,706,799,809,559,745,698,770,739,664,785,813,967,837,724,630,694,662,792,830,682,744,761,846,740,806,772,731,636,744,751,742,569,656,669,671,624,690,609,746,794,668,667,636,604,653,581,653,746,672,717,595,636,799,647,604,753,682,644,796,712,649,734,681,691,759,794,717,722,565,744,652,655,646,777,776,680,632,646,674,697,648,814,622,821,698,664,706,774,633,597,737,754,656,709,685,760,729,598,613,749,570,729,619,673,680,710,698,696,661,680,686,735,578,623,750,691,654,816,669,635,536,679,738,630,595,792,576,735,680,626,728,600,608,714,651,741,789,689,771,694,757,596,731,658,631,648,544,616,672,592,532,748,620,734,616,583,744,626,633,735,680,829,880,825,803,801,746,752,957,735,678,691,675,817,806,720,698,758,789,749,744,763,801,669,693,849,655,719,760,696,684,781,699,717,841,714,569,673,679,734,839,688,578,738,760,713,700,723,835,618,611,743,733,781,764,720,703,729,720,666,861,688,691,639,579,802,782,636,568,660,787,673,708,622,818,674,572,785,588,655,667,764,697,658,736,747,766,643,630,686,600,734,675,585,676,679,796,690,567,634,774,807,645,714,696,640,652,775,779,719,650,710,785,679,646,767,609,708,822,646,680,703,782,635,648,653,740,697,710,609,726,702,687,713,670,709,710,661,748,685,620,717,612,717,819,616,723,716,819,654,696,658,712,687,609,749,701,660,640,767,797,728,722,670,807,757,589,694,591,682,724,629,702,662,642,639,646,654,793,634,710,752,762,763,582,711,768,707,748,644,805,738,582,816,717,722,725,581,706,672,860,718,643,681,820,751,693,698,862,750,633,657,666,724,731,688,694,653,634,634,573,650,678,611,690,582,690,586,637,598,834,594,657,632,775,895,653,712,695,739,771,725,739,751,650,651,582,765,776,736,663,651,749,668,665,834,855,711,688,657,822,700,598,660,631,728,745,633,615,709,657,611,543,655,704,734,538,575,598,557,630,662,686,671,652,739,553,709,723,827,703,586,703,786,711,649,534,792,736,690,625,588,606,694,565,683,671,689,733,563,612,661,657,826,721,631,694,768,632,662,561,660,669,657,646,623,551,701,657,830,723,643,698,774,561,647,657,655,705,621,826,674,672,752,565,731,692,702,588,610,615,717,693,770,702,603,844,699,530,667,576,648,597,581,747,645,567,566,587,609,670,729,550,641,564,688,599,610,644,699,660,772,574,722,630,679,822,681,675,731,763,705,684,751,605,807,630,612,593,730,664,788,826,747,689,631,517,736,652,611,723,768,717,601,668,688,561,618,791,541,587,678,745,652,746,799,636,540,644,549,497,611,615,611,527,673,504,492,588,509,546,499,531,544,615,532,529,472,665,640,592,614,587,624,491,563,613,587,742,660,595,590,672,621,581,693,551,557,637,683,601,731,643,809,517,702,586,698,695,648,490,581,761,612,640,641,626,577,659,578,791,569,723,555,704,613,602,711,755,521,600,633,752,604,667,580,593,674,721,567,793,724,501,566,693,678,628,836,551,572,678,744,776,577,632,636,587,652,733,621,704,578,544,594,702,703,640,704,660,550,602,603,774,547,578,595,641,628,812,680,756,827,658,685,745,692,717,837,706,697,713,665,948,680,759,626,690,664,716],[81,94,93,69,61,85,97,68,64,88,55,72,89,86,69,83,66,74,95,94,81,79,76,75,94,88,90,93,73,98,94,89,69,90,71,79,79,80,73,95,72,56,71,86,82,96,63,77,97,74,102,72,71,67,86,90,91,96,81,80,65,91,66,89,75,88,91,69,83,81,80,76,67,80,80,77,94,79,95,81,97,57,90,61,92,86,96,90,85,69,70,86,64,95,83,79,78,65,92,86,87,74,65,97,95,80,87,70,103,75,93,62,75,85,88,91,84,87,75,59,82,72,68,95,97,89,74,81,74,74,84,86,75,100,84,90,88,89,89,75,92,67,63,61,72,86,97,79,86,59,90,84,69,96,85,72,72,96,90,88,71,73,69,94,82,83,79,88,94,76,89,68,89,88,71,78,66,75,83,73,76,79,70,86,66,90,80,78,76,95,78,82,62,89,88,75,96,97,97,93,85,67,88,78,76,83,61,80,87,71,77,90,74,95,79,99,73,93,67,71,83,89,56,95,71,81,83,83,95,88,88,67,82,69,75,100,67,79,80,81,92,51,96,78,98,89,83,76,80,68,72,83,92,58,93,67,92,67,71,101,91,86,72,87,63,91,105,70,89,67,77,84,101,71,95,88,86,69,68,74,43,91,87,83,85,68,90,83,66,101,96,86,75,64,93,100,85,63,71,86,99,98,101,67,93,67,81,78,74,73,55,79,84,62,92,56,94,83,75,103,103,80,72,66,93,95,97,55,72,78,75,92,88,63,82,88,83,66,91,73,66,76,93,65,86,68,85,68,82,95,102,86,62,79,116,90,93,62,73,80,82,85,95,74,85,65,95,85,90,82,79,79,72,77,86,73,69,67,94,87,91,65,69,76,91,97,95,69,71,83,70,100,103,78,94,67,75,96,97,72,69,64,97,64,77,74,63,68,97,98,87,77,78,74,79,86,75,69,95,84,85,65,106,79,92,90,80,77,89,77,65,54,102,72,83,74,70,65,88,114,74,75,69,98,76,89,83,63,88,88,84,101,98,78,68,80,76,86,83,79,92,84,67,88,78,68,78,88,96,65,68,79,76,90,90,73,77,76,96,88,85,70,76,85,81,99,83,53,80,82,75,90,80,78,88,71,92,78,67,73,91,85,68,88,90,74,104,85,80,71,84,94,73,76,67,85,64,85,84,81,69,71,94,59,88,68,97,75,61,82,103,87,86,95,98,89,73,72,78,86,90,76,75,81,72,63,92,90,87,72,76,96,70,96,82,64,72,83,77,96,94,67,84,81,77,87,74,57,84,65,82,93,83,95,71,77,71,84,78,98,84,83,75,84,85,91,65,76,88,80,77,94,91,77,79,75,75,86,74,74,85,91,67,103,77,95,75,77,85,70,83,86,63,87,83,91,93,69,75,73,59,86,92,77,81,80,81,87,74,99,67,74,89,73,92,86,83,89,54,54,89,75,77,71,87,78,88,82,84,94,87,91,81,100,85,104,65,85,83,68,83,76,70,87,69,67,78,75,76,77,84,61,98,76,83,73,91,85,91,92,89,81,80,80,65,78,90,95,75,96,72,73,95,92,70,72,86,84,87,96,76,73,77,71,78,108,90,76,86,64,74,67,83,79,87,86,66,83,81,90,77,85,89,60,84,83,91,95,71,77,84,98,97,77,75,57,83,74,62,101,62,99,80,85,86,81,96,74,70,75,104,80,84,79,67,81,78,90,87,77,81,75,92,74,66,84,69,89,88,98,78,70,71,99,74,70,92,85,79,91,87,70,82,68,91,74,90,84,81,60,79,79,77,89,89,94,89,93,73,87,61,78,83,77,90,88,95,60,86,65,79,68,89,84,81,76,87,92,64,78,81,100,83,65,64,70,89,79,84,93,97,92,86,77,90,67,103,83,91,83,73,59,75,74,76,67,66,102,91,88,80,73,90,81,84,89,85,79,95,82,95,63,89,54,84,98,68,67,71,86,83,53,69,90,99,87,79,71,92,69,86,74,92,95,93,73,76,66,100,69,90,88,84,56,89,69,87,59,61,97,97,74,81,90,88,71,74,81,102,98,67,84,75,64,100,63,101,96,69,64,75,83,94,54,70,88,83,76,75,64,102,81,74,80,90,92,66,85,55,86,97,87,101,92,73,74,72,76,67,90,95,72,75,75,108,79,57,64,91,88,68,76,75,82,83,98,86,92,71,80,82,79,88,91,84,68,66,80,98,77,72,81,77,102,76,82,79,71,89,90,80,88,60,72,86,83,76,97,89,79,77,77,99,71,85,82,88,95,74,81,79,82,80,94,71,80,60,88,81,57,82,101,85,76,83,79,79,60,91,79,85,89,69,74,71,83,81,101,67,97,61,90,90,63,76,108,87,86,84,56,102,76,79,79,65,87,65,98,73,83,93,89,73,89,63,86,76,70,93,109,87,71,92,68,89,62,90,81,69,85,97,52,100,80,88,63,88,52,64,90,87,86,81,91,86,67,84,67,83,86,103,72,76,79,73,83,82,76,80,88,97,65,77,76,92,84,87,89,87,75,91,69,62,73,91,61,72,82,81,91,101,76,85,97,72,80,59,83,76,81,88,72,74,95,89,66,70,87,92,93,83,71,94,62,75,72,95,89,87,89,65,59,97,102,86,50,77,85,90,95,80,70,97,72,76,98,92,79,85,66,57,82,80,79,88,53,99,92,80,90,93,62,86,76,82,94,86,79,79,66,73,70,99,91,84,51,104,87,74,88,93,56,77,76,59,85,98,80,85,64,72,86,102,91,86,40,96,81,93,103,84,60],[0.328,0.32,0.311,0.315,0.302,0.318,0.315,0.324,0.33,0.335,0.302,0.317,0.332,0.317,0.308,0.325,0.325,0.316,0.337,0.31,0.317,0.304,0.319,0.296,0.327,0.338,0.317,0.334,0.309,0.322,0.322,0.308,0.316,0.349,0.314,0.319,0.326,0.317,0.329,0.34,0.318,0.311,0.329,0.313,0.322,0.325,0.306,0.335,0.343,0.311,0.323,0.309,0.305,0.292,0.303,0.341,0.322,0.34,0.317,0.309,0.325,0.339,0.316,0.339,0.32,0.332,0.338,0.322,0.336,0.335,0.321,0.303,0.331,0.311,0.322,0.335,0.341,0.314,0.35,0.324,0.332,0.304,0.317,0.298,0.321,0.332,0.333,0.338,0.312,0.318,0.324,0.339,0.332,0.352,0.332,0.329,0.318,0.339,0.343,0.331,0.34,0.319,0.318,0.35,0.346,0.341,0.345,0.335,0.362,0.328,0.334,0.318,0.321,0.314,0.309,0.332,0.343,0.32,0.333,0.337,0.327,0.345,0.333,0.358,0.354,0.332,0.321,0.339,0.336,0.34,0.326,0.323,0.32,0.33,0.333,0.325,0.34,0.34,0.342,0.318,0.332,0.32,0.317,0.318,0.321,0.35,0.34,0.354,0.331,0.323,0.321,0.339,0.333,0.362,0.333,0.318,0.335,0.343,0.354,0.345,0.336,0.33,0.322,0.345,0.337,0.329,0.33,0.342,0.366,0.338,0.354,0.325,0.322,0.337,0.322,0.337,0.336,0.328,0.327,0.325,0.331,0.337,0.339,0.351,0.319,0.342,0.336,0.349,0.341,0.329,0.331,0.332,0.332,0.334,0.348,0.327,0.347,0.334,0.363,0.34,0.347,0.327,0.332,0.325,0.324,0.337,0.314,0.338,0.348,0.338,0.332,0.333,0.327,0.357,0.324,0.322,0.339,0.334,0.333,0.321,0.339,0.322,0.32,0.325,0.326,0.331,0.323,0.322,0.355,0.33,0.348,0.322,0.333,0.317,0.319,0.339,0.329,0.329,0.331,0.322,0.341,0.31,0.343,0.345,0.36,0.328,0.333,0.331,0.351,0.345,0.337,0.329,0.342,0.322,0.332,0.321,0.332,0.313,0.317,0.353,0.343,0.345,0.321,0.342,0.331,0.357,0.344,0.32,0.329,0.328,0.33,0.33,0.349,0.323,0.36,0.323,0.331,0.318,0.316,0.344,0.3,0.333,0.336,0.336,0.303,0.329,0.341,0.326,0.314,0.356,0.327,0.343,0.338,0.333,0.344,0.338,0.35,0.32,0.33,0.349,0.341,0.346,0.331,0.309,0.345,0.321,0.338,0.33,0.321,0.337,0.3,0.337,0.338,0.323,0.32,0.32,0.332,0.334,0.322,0.354,0.339,0.339,0.319,0.321,0.35,0.344,0.338,0.314,0.338,0.327,0.327,0.341,0.324,0.319,0.334,0.336,0.334,0.324,0.35,0.354,0.32,0.326,0.347,0.318,0.323,0.319,0.337,0.319,0.323,0.334,0.345,0.329,0.313,0.336,0.36,0.342,0.339,0.32,0.344,0.325,0.352,0.333,0.346,0.341,0.341,0.335,0.356,0.343,0.367,0.362,0.343,0.331,0.361,0.348,0.341,0.325,0.337,0.326,0.346,0.354,0.36,0.329,0.339,0.33,0.361,0.362,0.356,0.329,0.352,0.341,0.322,0.347,0.341,0.353,0.35,0.329,0.337,0.341,0.373,0.348,0.326,0.325,0.355,0.348,0.339,0.353,0.328,0.323,0.363,0.366,0.355,0.351,0.334,0.332,0.343,0.356,0.338,0.343,0.361,0.352,0.335,0.314,0.342,0.347,0.348,0.337,0.339,0.337,0.347,0.347,0.323,0.317,0.356,0.324,0.31,0.33,0.328,0.31,0.33,0.364,0.338,0.326,0.311,0.33,0.345,0.353,0.341,0.321,0.357,0.34,0.346,0.343,0.341,0.352,0.321,0.341,0.321,0.358,0.357,0.332,0.346,0.344,0.333,0.33,0.325,0.333,0.316,0.332,0.362,0.339,0.322,0.329,0.342,0.355,0.337,0.324,0.334,0.31,0.333,0.35,0.359,0.339,0.32,0.36,0.331,0.369,0.355,0.323,0.329,0.336,0.332,0.316,0.353,0.357,0.327,0.324,0.36,0.344,0.325,0.329,0.338,0.366,0.331,0.33,0.358,0.331,0.331,0.346,0.33,0.331,0.325,0.338,0.324,0.335,0.323,0.362,0.314,0.33,0.32,0.321,0.328,0.327,0.326,0.305,0.353,0.33,0.351,0.335,0.312,0.339,0.34,0.341,0.329,0.35,0.316,0.34,0.321,0.301,0.307,0.336,0.328,0.323,0.337,0.313,0.315,0.313,0.33,0.341,0.313,0.31,0.328,0.346,0.32,0.324,0.313,0.323,0.302,0.323,0.321,0.333,0.328,0.319,0.34,0.314,0.309,0.336,0.32,0.313,0.333,0.309,0.328,0.326,0.336,0.344,0.308,0.317,0.316,0.331,0.303,0.338,0.31,0.328,0.309,0.322,0.341,0.322,0.311,0.33,0.344,0.329,0.314,0.32,0.325,0.324,0.337,0.313,0.328,0.328,0.32,0.324,0.322,0.323,0.3,0.336,0.327,0.33,0.32,0.333,0.323,0.32,0.331,0.328,0.298,0.326,0.351,0.311,0.319,0.328,0.309,0.31,0.318,0.306,0.329,0.306,0.318,0.334,0.319,0.311,0.331,0.331,0.314,0.311,0.319,0.32,0.316,0.321,0.326,0.323,0.298,0.305,0.357,0.321,0.31,0.303,0.309,0.314,0.324,0.306,0.321,0.305,0.314,0.34,0.309,0.325,0.333,0.336,0.306,0.317,0.31,0.317,0.318,0.309,0.32,0.332,0.339,0.322,0.352,0.326,0.326,0.319,0.33,0.324,0.349,0.318,0.328,0.309,0.346,0.328,0.328,0.339,0.336,0.333,0.327,0.33,0.332,0.335,0.324,0.34,0.333,0.336,0.319,0.327,0.346,0.338,0.318,0.31,0.325,0.337,0.338,0.322,0.313,0.313,0.321,0.325,0.322,0.339,0.347,0.322,0.327,0.321,0.321,0.326,0.322,0.309,0.331,0.329,0.315,0.336,0.347,0.333,0.324,0.315,0.327,0.324,0.318,0.319,0.313,0.328,0.319,0.326,0.31,0.323,0.344,0.325,0.312,0.311,0.32,0.326,0.299,0.335,0.322,0.331,0.317,0.328,0.341,0.319,0.331,0.314,0.313,0.335,0.342,0.323,0.317,0.306,0.317,0.318,0.312,0.32,0.339,0.327,0.333,0.31,0.317,0.324,0.328,0.317,0.313,0.331,0.341,0.34,0.335,0.322,0.319,0.329,0.314,0.338,0.335,0.32,0.32,0.318,0.333,0.319,0.326,0.3,0.337,0.326,0.329,0.325,0.311,0.301,0.325,0.335,0.31,0.338,0.325,0.341,0.34,0.347,0.317,0.337,0.31,0.341,0.324,0.302,0.337,0.327,0.335,0.316,0.325,0.305,0.328,0.309,0.323,0.327,0.311,0.311,0.327,0.334,0.308,0.314,0.307,0.342,0.34,0.332,0.309,0.311,0.327,0.35,0.348,0.326,0.345,0.323,0.329,0.319,0.324,0.319,0.343,0.322,0.327,0.322,0.324,0.308,0.308,0.328,0.339,0.309,0.318,0.336,0.344,0.351,0.329,0.333,0.338,0.34,0.339,0.315,0.343,0.331,0.345,0.341,0.319,0.313,0.328,0.302,0.34,0.33,0.311,0.331,0.319,0.331,0.334,0.311,0.315,0.326,0.336,0.33,0.331,0.317,0.334,0.323,0.339,0.313,0.329,0.338,0.339,0.339,0.306,0.314,0.329,0.303,0.328,0.32,0.321,0.314,0.318,0.303,0.332,0.308,0.32,0.329,0.345,0.324,0.33,0.344,0.345,0.334,0.318,0.32,0.34,0.336,0.314,0.348,0.318,0.313,0.344,0.308,0.346,0.331,0.324,0.312,0.323,0.33,0.342,0.316,0.32,0.31,0.324,0.306,0.313,0.314,0.357,0.321,0.315,0.322,0.327,0.313,0.311,0.341,0.291,0.319,0.328,0.323,0.338,0.321,0.31,0.312,0.323,0.321,0.313,0.326,0.344,0.322,0.338,0.331,0.353,0.327,0.301,0.32,0.333,0.325,0.32,0.341,0.317,0.319,0.325,0.333,0.342,0.323,0.31,0.333,0.327,0.33,0.319,0.322,0.333,0.321,0.327,0.33,0.343,0.311,0.303,0.322,0.327,0.342,0.309,0.336,0.335,0.311,0.324,0.321,0.32,0.335,0.302,0.322,0.331,0.336,0.339,0.345,0.338,0.318,0.32,0.324,0.332,0.315,0.32,0.312,0.339,0.323,0.325,0.342,0.34,0.315,0.322,0.333,0.31,0.315,0.296,0.335,0.325,0.318,0.312,0.347,0.322,0.29,0.325,0.325,0.3,0.3,0.325,0.302,0.313,0.325,0.304,0.323,0.322,0.319,0.328,0.321,0.298,0.33,0.293,0.329,0.338,0.307,0.334,0.344,0.335,0.309,0.333,0.315,0.336,0.314,0.322,0.332,0.309,0.334,0.319,0.327,0.323,0.333,0.324,0.325,0.305,0.325,0.312,0.351,0.331,0.321,0.321,0.343,0.333,0.3,0.323,0.32,0.335,0.307,0.316,0.33,0.309,0.315,0.34,0.31,0.311,0.308,0.329,0.312,0.334,0.285,0.316,0.334,0.316,0.33,0.307,0.304,0.313,0.291,0.298,0.284,0.32,0.293,0.307,0.298,0.289,0.299,0.281,0.292,0.304,0.294,0.306,0.307,0.298,0.287,0.307,0.31,0.321,0.301,0.316,0.291,0.297,0.293,0.325,0.317,0.296,0.301,0.309,0.288,0.296,0.313,0.324,0.313,0.32,0.288,0.326,0.324,0.31,0.303,0.313,0.297,0.309,0.297,0.321,0.318,0.294,0.314,0.316,0.301,0.299,0.322,0.329,0.303,0.298,0.295,0.307,0.327,0.297,0.307,0.315,0.339,0.315,0.312,0.305,0.309,0.312,0.324,0.31,0.277,0.299,0.313,0.317,0.313,0.314,0.304,0.316,0.322,0.314,0.32,0.308,0.312,0.319,0.285,0.311,0.304,0.305,0.322,0.333,0.296,0.317,0.315,0.315,0.31,0.324,0.299,0.31,0.312,0.297,0.323,0.31,0.301,0.327,0.283,0.313,0.309,0.309,0.325,0.312,0.285,0.309,0.306,0.309,0.316,0.326,0.293,0.314,0.324,0.317,0.334,0.332,0.312,0.33,0.31,0.332,0.325,0.337,0.338,0.326,0.318,0.337,0.33,0.321,0.341,0.335,0.308],[0.418,0.389,0.417,0.415,0.378,0.422,0.411,0.381,0.436,0.422,0.371,0.4,0.433,0.374,0.382,0.437,0.39,0.386,0.453,0.404,0.4,0.395,0.38,0.369,0.397,0.421,0.394,0.446,0.407,0.428,0.413,0.387,0.413,0.461,0.401,0.388,0.408,0.396,0.41,0.434,0.388,0.374,0.415,0.402,0.375,0.425,0.36,0.391,0.444,0.369,0.395,0.368,0.349,0.348,0.368,0.425,0.402,0.46,0.413,0.383,0.416,0.401,0.386,0.451,0.401,0.42,0.436,0.378,0.425,0.415,0.403,0.362,0.399,0.39,0.379,0.424,0.422,0.383,0.436,0.378,0.413,0.373,0.371,0.339,0.408,0.402,0.403,0.419,0.454,0.39,0.418,0.405,0.415,0.454,0.407,0.411,0.394,0.417,0.441,0.416,0.416,0.4,0.405,0.441,0.412,0.426,0.429,0.394,0.478,0.397,0.447,0.387,0.381,0.402,0.389,0.415,0.439,0.445,0.44,0.406,0.415,0.408,0.429,0.447,0.443,0.448,0.408,0.424,0.415,0.444,0.433,0.415,0.397,0.413,0.399,0.431,0.408,0.42,0.427,0.369,0.438,0.403,0.39,0.389,0.382,0.433,0.422,0.462,0.399,0.373,0.413,0.435,0.412,0.444,0.422,0.404,0.436,0.428,0.437,0.458,0.448,0.412,0.388,0.417,0.406,0.456,0.391,0.432,0.463,0.407,0.458,0.411,0.411,0.425,0.387,0.405,0.433,0.426,0.419,0.39,0.424,0.455,0.424,0.435,0.422,0.464,0.432,0.457,0.433,0.449,0.435,0.409,0.411,0.425,0.432,0.42,0.425,0.445,0.461,0.412,0.447,0.397,0.416,0.424,0.422,0.431,0.42,0.446,0.463,0.418,0.421,0.435,0.434,0.454,0.44,0.425,0.446,0.453,0.411,0.428,0.409,0.408,0.396,0.409,0.395,0.423,0.391,0.416,0.45,0.407,0.423,0.4,0.391,0.391,0.396,0.423,0.425,0.468,0.407,0.386,0.429,0.393,0.434,0.432,0.472,0.458,0.457,0.418,0.444,0.455,0.449,0.406,0.436,0.397,0.423,0.387,0.431,0.392,0.409,0.458,0.433,0.443,0.401,0.414,0.396,0.438,0.46,0.405,0.457,0.403,0.413,0.417,0.475,0.405,0.491,0.416,0.446,0.395,0.401,0.445,0.375,0.421,0.431,0.427,0.368,0.419,0.431,0.401,0.374,0.453,0.417,0.419,0.42,0.388,0.41,0.425,0.454,0.404,0.454,0.455,0.433,0.423,0.409,0.403,0.444,0.413,0.449,0.408,0.412,0.423,0.379,0.403,0.417,0.398,0.409,0.39,0.437,0.418,0.395,0.455,0.432,0.422,0.381,0.381,0.419,0.442,0.425,0.39,0.455,0.43,0.405,0.442,0.412,0.38,0.439,0.43,0.451,0.419,0.458,0.483,0.409,0.423,0.451,0.409,0.425,0.426,0.433,0.396,0.387,0.435,0.439,0.414,0.393,0.399,0.445,0.46,0.441,0.388,0.471,0.43,0.472,0.429,0.429,0.435,0.423,0.411,0.47,0.447,0.47,0.455,0.438,0.409,0.477,0.425,0.431,0.403,0.407,0.432,0.43,0.45,0.458,0.4,0.424,0.402,0.442,0.472,0.455,0.399,0.446,0.469,0.395,0.459,0.436,0.447,0.448,0.42,0.429,0.451,0.467,0.472,0.443,0.395,0.42,0.433,0.42,0.426,0.384,0.427,0.434,0.453,0.446,0.431,0.419,0.393,0.455,0.434,0.426,0.411,0.479,0.457,0.415,0.393,0.453,0.447,0.463,0.433,0.444,0.402,0.448,0.461,0.415,0.373,0.436,0.399,0.387,0.396,0.389,0.394,0.394,0.46,0.397,0.395,0.374,0.409,0.468,0.421,0.441,0.385,0.462,0.448,0.416,0.426,0.429,0.463,0.396,0.417,0.389,0.467,0.478,0.415,0.395,0.403,0.407,0.418,0.398,0.409,0.425,0.405,0.436,0.423,0.385,0.404,0.407,0.485,0.414,0.396,0.438,0.389,0.432,0.472,0.457,0.431,0.401,0.447,0.422,0.475,0.472,0.42,0.393,0.397,0.398,0.384,0.441,0.425,0.406,0.412,0.436,0.452,0.387,0.407,0.402,0.484,0.388,0.407,0.469,0.42,0.408,0.413,0.395,0.38,0.414,0.411,0.396,0.409,0.422,0.434,0.346,0.409,0.397,0.383,0.378,0.385,0.386,0.39,0.435,0.394,0.426,0.393,0.389,0.406,0.427,0.395,0.431,0.436,0.388,0.398,0.347,0.338,0.364,0.383,0.382,0.383,0.407,0.359,0.364,0.339,0.375,0.391,0.37,0.342,0.406,0.386,0.377,0.381,0.386,0.402,0.355,0.375,0.393,0.414,0.393,0.401,0.401,0.374,0.39,0.391,0.403,0.35,0.416,0.347,0.394,0.359,0.396,0.42,0.357,0.365,0.387,0.389,0.358,0.398,0.362,0.383,0.381,0.357,0.424,0.4,0.396,0.37,0.395,0.391,0.392,0.379,0.399,0.391,0.409,0.345,0.395,0.382,0.384,0.385,0.37,0.408,0.366,0.391,0.363,0.405,0.38,0.373,0.396,0.358,0.376,0.419,0.35,0.379,0.403,0.386,0.387,0.383,0.37,0.365,0.351,0.345,0.373,0.339,0.382,0.402,0.361,0.385,0.391,0.381,0.364,0.359,0.369,0.384,0.39,0.363,0.394,0.398,0.348,0.359,0.42,0.385,0.383,0.37,0.368,0.387,0.378,0.351,0.391,0.352,0.375,0.421,0.373,0.396,0.395,0.399,0.355,0.369,0.351,0.398,0.368,0.337,0.368,0.419,0.403,0.418,0.43,0.401,0.432,0.415,0.427,0.422,0.451,0.373,0.412,0.371,0.428,0.43,0.401,0.434,0.418,0.428,0.41,0.403,0.378,0.428,0.43,0.378,0.43,0.446,0.381,0.395,0.415,0.404,0.398,0.363,0.387,0.43,0.424,0.381,0.39,0.37,0.385,0.428,0.379,0.401,0.43,0.39,0.4,0.374,0.388,0.399,0.375,0.327,0.428,0.427,0.363,0.43,0.429,0.386,0.39,0.392,0.376,0.385,0.424,0.388,0.401,0.382,0.379,0.407,0.375,0.385,0.425,0.401,0.383,0.347,0.368,0.412,0.348,0.379,0.381,0.425,0.361,0.391,0.441,0.381,0.397,0.395,0.356,0.384,0.432,0.371,0.399,0.348,0.37,0.385,0.362,0.369,0.404,0.404,0.407,0.363,0.371,0.384,0.375,0.351,0.377,0.421,0.4,0.421,0.409,0.393,0.401,0.413,0.356,0.369,0.427,0.375,0.397,0.379,0.418,0.401,0.386,0.344,0.416,0.381,0.373,0.383,0.351,0.36,0.375,0.384,0.366,0.436,0.383,0.419,0.407,0.433,0.375,0.413,0.35,0.373,0.418,0.349,0.428,0.388,0.455,0.396,0.396,0.35,0.398,0.367,0.376,0.408,0.359,0.381,0.376,0.364,0.359,0.383,0.38,0.413,0.436,0.378,0.365,0.37,0.386,0.381,0.409,0.367,0.413,0.388,0.448,0.381,0.388,0.345,0.425,0.385,0.4,0.388,0.342,0.356,0.342,0.4,0.405,0.383,0.377,0.419,0.456,0.429,0.403,0.41,0.396,0.384,0.415,0.344,0.422,0.412,0.448,0.402,0.408,0.35,0.406,0.346,0.396,0.416,0.348,0.404,0.365,0.401,0.409,0.363,0.363,0.396,0.424,0.37,0.361,0.379,0.393,0.379,0.392,0.355,0.399,0.402,0.432,0.375,0.379,0.352,0.388,0.351,0.388,0.385,0.348,0.359,0.374,0.358,0.381,0.359,0.376,0.393,0.465,0.386,0.387,0.444,0.436,0.38,0.41,0.385,0.436,0.418,0.389,0.417,0.402,0.346,0.444,0.352,0.448,0.413,0.375,0.381,0.383,0.388,0.405,0.365,0.334,0.358,0.402,0.318,0.356,0.349,0.424,0.359,0.365,0.347,0.371,0.349,0.34,0.375,0.34,0.352,0.389,0.361,0.395,0.391,0.337,0.345,0.359,0.341,0.346,0.373,0.417,0.328,0.368,0.358,0.401,0.392,0.366,0.359,0.394,0.365,0.389,0.386,0.348,0.361,0.382,0.391,0.402,0.402,0.335,0.365,0.375,0.371,0.363,0.37,0.377,0.356,0.365,0.389,0.394,0.37,0.366,0.378,0.364,0.401,0.369,0.378,0.35,0.329,0.368,0.373,0.373,0.391,0.33,0.358,0.365,0.377,0.427,0.389,0.401,0.348,0.357,0.372,0.383,0.387,0.39,0.376,0.381,0.371,0.388,0.393,0.364,0.338,0.378,0.389,0.371,0.405,0.351,0.407,0.357,0.361,0.385,0.398,0.397,0.329,0.378,0.373,0.366,0.342,0.405,0.34,0.353,0.37,0.329,0.372,0.343,0.351,0.36,0.384,0.35,0.416,0.332,0.378,0.385,0.326,0.404,0.401,0.428,0.363,0.415,0.362,0.436,0.394,0.374,0.391,0.348,0.382,0.358,0.403,0.365,0.37,0.365,0.392,0.356,0.406,0.391,0.409,0.379,0.358,0.38,0.414,0.415,0.319,0.384,0.357,0.422,0.345,0.387,0.352,0.338,0.359,0.408,0.359,0.351,0.344,0.376,0.372,0.398,0.329,0.346,0.361,0.359,0.378,0.339,0.352,0.352,0.318,0.366,0.311,0.389,0.327,0.385,0.317,0.319,0.35,0.315,0.318,0.343,0.333,0.343,0.341,0.346,0.336,0.372,0.372,0.395,0.349,0.378,0.32,0.372,0.359,0.376,0.364,0.33,0.332,0.369,0.325,0.317,0.357,0.38,0.372,0.379,0.326,0.424,0.409,0.376,0.354,0.38,0.331,0.395,0.36,0.406,0.365,0.337,0.362,0.382,0.342,0.374,0.378,0.428,0.392,0.368,0.355,0.363,0.4,0.341,0.358,0.364,0.439,0.379,0.374,0.34,0.358,0.335,0.399,0.416,0.327,0.364,0.384,0.382,0.385,0.371,0.35,0.387,0.416,0.39,0.353,0.372,0.38,0.395,0.315,0.379,0.344,0.34,0.427,0.418,0.348,0.387,0.391,0.389,0.382,0.392,0.348,0.38,0.4,0.363,0.365,0.371,0.381,0.382,0.301,0.353,0.354,0.357,0.43,0.37,0.315,0.403,0.381,0.359,0.414,0.403,0.351,0.387,0.403,0.377,0.372,0.417,0.388,0.411,0.351,0.386,0.38,0.4,0.412,0.403,0.361,0.426,0.39,0.394,0.441,0.394,0.373],[0.259,0.247,0.247,0.26,0.24,0.255,0.251,0.251,0.274,0.268,0.236,0.265,0.274,0.252,0.244,0.259,0.26,0.249,0.265,0.238,0.255,0.243,0.247,0.234,0.269,0.271,0.24,0.273,0.245,0.261,0.25,0.243,0.257,0.28,0.256,0.252,0.256,0.25,0.258,0.277,0.247,0.258,0.275,0.253,0.257,0.261,0.247,0.264,0.263,0.244,0.253,0.244,0.237,0.233,0.242,0.273,0.244,0.283,0.249,0.242,0.25,0.258,0.259,0.268,0.257,0.268,0.272,0.248,0.263,0.268,0.254,0.247,0.274,0.248,0.252,0.262,0.273,0.249,0.267,0.256,0.26,0.242,0.246,0.236,0.257,0.263,0.247,0.276,0.248,0.25,0.253,0.263,0.268,0.27,0.255,0.258,0.247,0.264,0.261,0.26,0.268,0.26,0.259,0.285,0.27,0.263,0.274,0.27,0.283,0.262,0.258,0.252,0.242,0.258,0.257,0.263,0.263,0.26,0.266,0.258,0.251,0.27,0.267,0.28,0.278,0.263,0.247,0.262,0.263,0.271,0.254,0.263,0.269,0.268,0.264,0.253,0.279,0.266,0.271,0.242,0.255,0.258,0.25,0.265,0.262,0.281,0.26,0.283,0.264,0.251,0.25,0.275,0.272,0.279,0.271,0.246,0.267,0.268,0.28,0.287,0.267,0.26,0.261,0.284,0.275,0.262,0.264,0.275,0.29,0.256,0.274,0.263,0.251,0.287,0.254,0.274,0.268,0.263,0.259,0.256,0.267,0.27,0.277,0.269,0.268,0.28,0.257,0.28,0.27,0.274,0.264,0.255,0.271,0.274,0.276,0.258,0.287,0.264,0.285,0.26,0.267,0.263,0.263,0.272,0.259,0.269,0.255,0.278,0.284,0.262,0.256,0.265,0.269,0.281,0.27,0.262,0.261,0.271,0.267,0.272,0.272,0.256,0.263,0.27,0.253,0.259,0.259,0.258,0.276,0.262,0.27,0.259,0.257,0.256,0.261,0.27,0.274,0.267,0.265,0.252,0.282,0.253,0.27,0.281,0.282,0.268,0.268,0.25,0.276,0.275,0.272,0.264,0.267,0.259,0.262,0.248,0.266,0.249,0.249,0.268,0.27,0.267,0.26,0.273,0.27,0.27,0.278,0.258,0.266,0.26,0.268,0.263,0.284,0.268,0.289,0.259,0.263,0.245,0.254,0.267,0.24,0.266,0.263,0.274,0.243,0.256,0.277,0.258,0.247,0.271,0.254,0.261,0.267,0.261,0.271,0.264,0.279,0.265,0.266,0.279,0.282,0.267,0.26,0.246,0.277,0.246,0.268,0.253,0.249,0.274,0.248,0.261,0.262,0.256,0.264,0.253,0.272,0.261,0.256,0.275,0.261,0.259,0.244,0.253,0.275,0.267,0.268,0.253,0.269,0.261,0.261,0.267,0.26,0.248,0.266,0.261,0.268,0.262,0.278,0.292,0.26,0.264,0.271,0.266,0.255,0.251,0.272,0.253,0.249,0.267,0.264,0.26,0.247,0.252,0.288,0.266,0.27,0.258,0.275,0.263,0.28,0.265,0.271,0.272,0.267,0.256,0.286,0.274,0.288,0.294,0.275,0.262,0.278,0.288,0.257,0.246,0.27,0.266,0.263,0.277,0.27,0.251,0.267,0.254,0.269,0.278,0.27,0.257,0.283,0.275,0.256,0.277,0.266,0.279,0.278,0.257,0.277,0.272,0.289,0.288,0.261,0.263,0.267,0.282,0.266,0.273,0.264,0.265,0.279,0.282,0.259,0.275,0.259,0.252,0.269,0.271,0.262,0.274,0.293,0.28,0.272,0.246,0.272,0.273,0.28,0.264,0.271,0.262,0.272,0.291,0.264,0.248,0.28,0.263,0.252,0.26,0.266,0.249,0.259,0.288,0.257,0.264,0.254,0.253,0.276,0.274,0.258,0.261,0.289,0.266,0.272,0.27,0.268,0.291,0.263,0.273,0.253,0.286,0.288,0.258,0.259,0.259,0.264,0.268,0.26,0.27,0.258,0.262,0.287,0.26,0.255,0.262,0.271,0.28,0.258,0.255,0.274,0.244,0.27,0.274,0.283,0.276,0.251,0.281,0.256,0.293,0.287,0.256,0.257,0.262,0.267,0.252,0.279,0.288,0.262,0.27,0.288,0.265,0.256,0.266,0.265,0.287,0.253,0.267,0.284,0.259,0.262,0.267,0.264,0.26,0.27,0.265,0.264,0.275,0.273,0.275,0.248,0.267,0.263,0.261,0.258,0.264,0.257,0.248,0.279,0.254,0.274,0.267,0.252,0.26,0.276,0.272,0.267,0.279,0.254,0.259,0.246,0.243,0.254,0.261,0.26,0.266,0.256,0.246,0.256,0.248,0.268,0.277,0.252,0.235,0.261,0.258,0.253,0.255,0.255,0.263,0.244,0.262,0.25,0.263,0.258,0.254,0.269,0.255,0.253,0.262,0.258,0.254,0.247,0.244,0.264,0.253,0.271,0.28,0.246,0.244,0.256,0.248,0.241,0.263,0.244,0.255,0.246,0.255,0.27,0.257,0.25,0.245,0.272,0.26,0.263,0.258,0.265,0.267,0.259,0.242,0.267,0.262,0.256,0.265,0.25,0.256,0.241,0.254,0.255,0.259,0.257,0.259,0.262,0.256,0.259,0.265,0.234,0.252,0.277,0.256,0.261,0.271,0.247,0.245,0.242,0.239,0.261,0.24,0.259,0.276,0.247,0.246,0.269,0.261,0.243,0.241,0.251,0.257,0.25,0.258,0.263,0.26,0.242,0.238,0.283,0.261,0.261,0.244,0.246,0.261,0.25,0.244,0.259,0.248,0.257,0.274,0.251,0.256,0.263,0.263,0.239,0.247,0.247,0.257,0.248,0.249,0.252,0.268,0.258,0.258,0.278,0.252,0.264,0.258,0.266,0.263,0.272,0.253,0.262,0.252,0.276,0.261,0.265,0.268,0.262,0.26,0.254,0.264,0.26,0.272,0.26,0.263,0.266,0.269,0.25,0.258,0.271,0.255,0.256,0.247,0.254,0.284,0.263,0.255,0.252,0.251,0.255,0.261,0.254,0.263,0.271,0.252,0.253,0.25,0.261,0.253,0.253,0.236,0.267,0.269,0.246,0.263,0.282,0.251,0.254,0.253,0.255,0.265,0.253,0.261,0.252,0.261,0.263,0.264,0.247,0.257,0.267,0.264,0.245,0.247,0.255,0.255,0.233,0.264,0.253,0.269,0.247,0.252,0.283,0.249,0.26,0.247,0.244,0.265,0.271,0.264,0.268,0.244,0.262,0.265,0.251,0.257,0.276,0.259,0.266,0.255,0.259,0.258,0.265,0.252,0.261,0.273,0.272,0.269,0.27,0.26,0.261,0.262,0.239,0.265,0.274,0.257,0.271,0.25,0.277,0.261,0.264,0.241,0.273,0.262,0.249,0.264,0.25,0.24,0.247,0.27,0.255,0.277,0.256,0.266,0.274,0.274,0.26,0.273,0.251,0.262,0.266,0.247,0.285,0.264,0.279,0.257,0.262,0.247,0.256,0.236,0.26,0.273,0.257,0.254,0.253,0.264,0.249,0.262,0.25,0.273,0.283,0.265,0.251,0.259,0.262,0.277,0.273,0.261,0.286,0.263,0.275,0.265,0.257,0.257,0.267,0.259,0.27,0.266,0.255,0.248,0.244,0.275,0.284,0.251,0.256,0.261,0.283,0.282,0.269,0.275,0.264,0.258,0.269,0.256,0.282,0.263,0.28,0.278,0.264,0.25,0.266,0.239,0.266,0.272,0.242,0.269,0.246,0.278,0.278,0.251,0.244,0.258,0.267,0.259,0.264,0.264,0.256,0.261,0.271,0.258,0.268,0.264,0.276,0.267,0.254,0.245,0.267,0.245,0.258,0.257,0.252,0.248,0.248,0.249,0.253,0.25,0.254,0.261,0.281,0.255,0.266,0.278,0.274,0.269,0.264,0.254,0.277,0.266,0.258,0.282,0.26,0.244,0.281,0.24,0.279,0.274,0.249,0.256,0.253,0.27,0.27,0.252,0.245,0.243,0.263,0.235,0.251,0.255,0.28,0.263,0.257,0.256,0.269,0.251,0.246,0.274,0.235,0.246,0.269,0.246,0.272,0.267,0.247,0.246,0.26,0.25,0.244,0.252,0.275,0.246,0.259,0.255,0.271,0.261,0.249,0.254,0.261,0.248,0.25,0.271,0.244,0.256,0.264,0.254,0.269,0.263,0.244,0.259,0.273,0.256,0.249,0.256,0.264,0.254,0.251,0.268,0.26,0.255,0.247,0.263,0.259,0.272,0.244,0.272,0.254,0.235,0.263,0.247,0.261,0.274,0.229,0.252,0.265,0.272,0.266,0.266,0.267,0.253,0.247,0.256,0.254,0.256,0.254,0.251,0.261,0.263,0.253,0.27,0.251,0.246,0.261,0.26,0.249,0.261,0.244,0.262,0.259,0.255,0.257,0.261,0.252,0.231,0.258,0.25,0.241,0.238,0.254,0.24,0.25,0.266,0.229,0.26,0.246,0.249,0.254,0.252,0.233,0.274,0.233,0.247,0.275,0.23,0.27,0.257,0.262,0.251,0.259,0.253,0.27,0.249,0.238,0.259,0.244,0.27,0.242,0.262,0.237,0.249,0.251,0.249,0.238,0.27,0.246,0.262,0.263,0.238,0.258,0.265,0.251,0.23,0.253,0.247,0.277,0.237,0.242,0.24,0.24,0.254,0.268,0.24,0.242,0.235,0.249,0.241,0.277,0.225,0.234,0.242,0.253,0.251,0.252,0.225,0.236,0.227,0.242,0.228,0.273,0.234,0.235,0.231,0.23,0.237,0.228,0.214,0.24,0.233,0.252,0.239,0.249,0.224,0.24,0.24,0.255,0.238,0.251,0.225,0.248,0.235,0.243,0.249,0.233,0.236,0.24,0.238,0.225,0.242,0.277,0.245,0.263,0.223,0.263,0.258,0.24,0.232,0.254,0.231,0.26,0.237,0.251,0.255,0.236,0.256,0.249,0.239,0.235,0.258,0.279,0.248,0.251,0.234,0.238,0.251,0.239,0.238,0.246,0.273,0.25,0.238,0.237,0.24,0.245,0.254,0.256,0.221,0.235,0.25,0.265,0.252,0.254,0.228,0.248,0.258,0.251,0.247,0.249,0.247,0.253,0.229,0.239,0.242,0.25,0.252,0.272,0.246,0.253,0.258,0.264,0.246,0.272,0.231,0.249,0.252,0.238,0.25,0.246,0.239,0.252,0.22,0.247,0.25,0.251,0.255,0.244,0.219,0.252,0.252,0.25,0.258,0.271,0.227,0.248,0.258,0.253,0.257,0.27,0.245,0.248,0.246,0.263,0.25,0.268,0.26,0.252,0.24,0.267,0.26,0.268,0.278,0.271,0.25],[\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\"],[null,\"4\",\"5\",null,null,null,\"2\",null,null,\"6\",null,null,null,null,null,null,null,null,\"3\",\"4\",null,null,null,null,\"4\",\"6\",null,\"5\",null,\"1\",\"5\",null,null,null,null,null,null,null,null,\"4\",null,null,null,null,null,\"3\",null,null,\"2\",null,\"1\",null,null,null,null,\"7\",\"6\",\"3\",null,null,null,\"6\",null,null,null,null,\"6\",null,null,null,null,null,null,null,null,null,\"4\",null,\"3\",null,\"1\",null,null,null,\"5\",null,\"2\",\"7\",null,null,null,null,null,\"3\",null,null,null,null,\"5\",null,null,null,null,\"2\",\"3\",null,\"7\",null,\"1\",null,\"4\",null,null,null,null,\"6\",null,null,null,null,null,null,null,\"3\",\"2\",\"6\",null,null,null,null,null,null,null,\"1\",\"7\",\"5\",null,null,null,null,\"4\",null,null,null,null,null,\"2\",null,null,null,\"3\",null,null,\"1\",\"5\",null,null,\"1\",\"3\",null,null,null,null,\"2\",null,null,null,null,\"2\",null,\"4\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",null,null,null,null,\"5\",null,\"2\",\"1\",\"1\",\"4\",null,null,\"5\",null,null,\"6\",null,null,null,null,null,\"4\",null,\"3\",null,\"2\",null,null,null,null,null,\"5\",null,\"3\",null,null,null,null,\"3\",null,null,null,\"6\",null,null,\"1\",null,null,null,null,\"6\",null,\"4\",null,\"3\",null,null,null,null,null,null,null,\"6\",null,\"5\",null,\"6\",null,null,\"2\",null,null,null,null,null,null,\"1\",null,null,null,null,null,\"1\",null,\"4\",\"7\",null,null,null,null,null,\"5\",null,null,null,null,\"6\",null,null,\"1\",\"3\",null,null,null,null,\"2\",null,null,null,null,\"3\",\"4\",\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,\"7\",null,null,\"1\",\"1\",null,null,null,null,\"6\",\"5\",null,null,null,null,\"5\",\"7\",null,null,null,null,null,\"6\",null,null,null,\"4\",null,null,null,null,null,null,\"3\",\"2\",null,null,null,\"1\",null,\"4\",null,null,null,null,null,\"2\",null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,\"3\",\"5\",\"4\",null,null,null,\"4\",\"1\",\"2\",null,null,null,null,\"2\",\"1\",null,\"6\",null,null,null,\"4\",null,null,null,\"4\",null,null,null,null,null,\"4\",\"3\",null,null,null,null,null,null,null,null,\"5\",null,null,null,\"2\",null,\"5\",\"6\",null,null,\"7\",null,null,null,\"3\",null,null,null,null,null,null,\"1\",null,null,null,\"4\",null,null,null,null,\"8\",null,null,\"1\",\"2\",null,null,null,null,\"6\",null,null,\"4\",\"7\",null,null,null,null,null,null,\"3\",null,null,null,null,\"5\",\"5\",null,null,null,\"2\",\"6\",null,null,null,null,null,\"1\",null,null,null,null,null,\"5\",null,null,null,null,\"3\",null,null,null,\"4\",null,null,\"6\",\"5\",null,\"1\",null,null,null,null,\"4\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,\"3\",\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,\"2\",null,null,null,null,null,\"2\",\"3\",null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,\"1\",null,null,null,null,null,\"4\",null,null,\"4\",null,null,null,\"3\",null,null,null,null,null,null,null,null,null,null,\"1\",null,\"2\",null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,\"3\",null,null,\"4\",null,null,\"4\",null,null,null,null,null,null,null,null,\"3\",null,null,null,\"2\",null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,\"4\",null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,\"3\",\"4\",null,null,null,null,null,\"2\",null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"4\",\"3\",null,null,null,null,null,null,null,null,null,null,null,\"1\",null,\"2\",null,null,null,null,\"2\",null,null,null,\"1\",null,\"4\",null,null,null,null,null,null,null,null,null,\"3\",null,null,null,null,null,null,\"2\",null,null,null,\"1\",null,null,null,null,null,\"3\",null,null,null,null,null,null,\"4\",null,null,null,null,null,null,null,\"4\",null,null,\"2\",null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,\"3\",null,null,null,null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,null,\"1\",null,\"4\",null,null,null,null,null,null,null,null,\"1\",null,\"4\",null,null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,\"1\",null,\"4\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",\"4\",null,null,null,null,\"3\",null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,\"4\",null,null,null,null,null,\"3\",null,\"2\",null,null,null,null,null,null,null,\"3\",null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,\"2\",null,\"4\",null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,\"3\",null,\"4\",null,null,null,null,null,\"2\",null,null,null,null,\"1\",null,null,null,null,null,null,null,null,\"4\",null,\"3\",null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,\"2\",null,\"3\",null,null,null,\"1\",null,null,null,null,\"2\",null,null,null,null,null,null,\"3\",null,null,null,null,null,\"4\",null,null,null,null,\"4\",\"1\",null,null,null,null,null,null,null,null,null,null,\"3\",null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,\"1\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,\"1\",null,null],[null,\"5\",\"4\",null,null,null,\"4\",null,null,\"2\",null,null,null,null,null,null,null,null,\"3\",\"4\",null,null,null,null,\"1\",\"3\",null,\"5\",null,\"4\",\"4\",null,null,null,null,null,null,null,null,\"3\",null,null,null,null,null,\"3\",null,null,\"4\",null,\"4\",null,null,null,null,\"1\",\"4\",\"2\",null,null,null,\"4\",null,null,null,null,\"4\",null,null,null,null,null,null,null,null,null,\"4\",null,\"3\",null,\"3\",null,null,null,\"1\",null,\"4\",\"2\",null,null,null,null,null,\"4\",null,null,null,null,\"4\",null,null,null,null,\"3\",\"3\",null,\"4\",null,\"1\",null,\"2\",null,null,null,null,\"4\",null,null,null,null,null,null,null,\"3\",\"4\",\"4\",null,null,null,null,null,null,null,\"4\",\"3\",\"4\",null,null,null,null,\"1\",null,null,null,null,null,\"2\",null,null,null,\"3\",null,null,\"1\",\"4\",null,null,\"3\",\"2\",null,null,null,null,\"4\",null,null,null,null,\"4\",null,\"4\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,\"4\",null,\"4\",\"3\",\"4\",\"3\",null,null,\"4\",null,null,\"1\",null,null,null,null,null,\"4\",null,\"4\",null,\"1\",null,null,null,null,null,\"2\",null,\"3\",null,null,null,null,\"4\",null,null,null,\"4\",null,null,\"3\",null,null,null,null,\"4\",null,\"4\",null,\"1\",null,null,null,null,null,null,null,\"3\",null,\"4\",null,\"4\",null,null,\"3\",null,null,null,null,null,null,\"2\",null,null,null,null,null,\"4\",null,\"3\",\"3\",null,null,null,null,null,\"1\",null,null,null,null,\"4\",null,null,\"2\",\"4\",null,null,null,null,\"4\",null,null,null,null,\"1\",\"4\",\"4\",null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",null,null,\"4\",\"4\",null,null,null,null,\"2\",\"3\",null,null,null,null,\"1\",\"3\",null,null,null,null,null,\"4\",null,null,null,\"4\",null,null,null,null,null,null,\"2\",\"4\",null,null,null,\"3\",null,\"4\",null,null,null,null,null,\"4\",null,null,null,\"4\",null,null,null,null,null,null,null,null,null,null,null,\"2\",\"1\",\"4\",null,null,null,\"3\",\"4\",\"3\",null,null,null,null,\"4\",\"2\",null,\"3\",null,null,null,\"4\",null,null,null,\"4\",null,null,null,null,null,\"3\",\"1\",null,null,null,null,null,null,null,null,\"4\",null,null,null,\"3\",null,\"4\",\"4\",null,null,\"3\",null,null,null,\"4\",null,null,null,null,null,null,\"1\",null,null,null,\"2\",null,null,null,null,\"4\",null,null,\"3\",\"3\",null,null,null,null,\"2\",null,null,\"1\",\"4\",null,null,null,null,null,null,\"4\",null,null,null,null,\"4\",\"4\",null,null,null,\"2\",\"3\",null,null,null,null,null,\"4\",null,null,null,null,null,\"4\",null,null,null,null,\"1\",null,null,null,\"4\",null,null,\"3\",\"4\",null,\"3\",null,null,null,null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,\"1\",\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",null,\"3\",null,null,null,null,null,\"1\",\"2\",null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,\"3\",null,null,null,null,null,\"3\",null,null,\"3\",null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,\"2\",null,\"3\",null,null,null,null,null,null,null,null,null,null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,\"2\",null,null,\"3\",null,null,\"3\",null,null,null,null,null,null,null,null,\"1\",null,null,null,\"3\",null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",null,null,null,null,\"1\",null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,\"2\",\"3\",null,null,null,null,null,\"3\",null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",\"3\",null,null,null,null,null,null,null,null,null,null,null,\"2\",null,\"3\",null,null,null,null,\"3\",null,null,null,\"1\",null,\"3\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,\"1\",null,null,null,\"3\",null,null,null,null,null,\"3\",null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,\"3\",null,null,\"3\",null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,null,\"3\",null,\"1\",null,null,null,null,null,null,null,null,\"2\",null,\"3\",null,null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,\"1\",null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",\"2\",null,null,null,null,\"1\",null,\"3\",null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,\"3\",null,null,null,null,null,\"2\",null,\"3\",null,null,null,null,null,null,null,\"2\",null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,\"3\",null,\"3\",null,null,null,null,null,\"3\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,\"1\",null,\"3\",null,null,null,null,null,\"3\",null,null,null,null,\"3\",null,null,null,null,null,null,null,null,\"2\",null,\"1\",null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"3\",null,\"1\",null,\"3\",null,null,null,\"1\",null,null,null,null,\"2\",null,null,null,null,null,null,\"3\",null,null,null,null,null,\"3\",null,null,null,null,\"3\",\"2\",null,null,null,null,null,null,null,null,null,null,\"3\",null,\"1\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,\"1\",null,null,null,null,null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"2\",null,null,null,\"1\",null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,null,\"2\",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,\"1\",null,null,\"2\",null,null],[\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"163\",\"162\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"161\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"161\",\"162\",\"162\",\"161\",\"162\",\"161\",\"161\",\"162\",\"163\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"161\",\"163\",\"163\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"160\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"160\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"163\",\"164\",\"162\",\"162\",\"162\",\"164\",\"162\",\"162\",\"160\",\"161\",\"162\",\"162\",\"163\",\"161\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"163\",\"160\",\"161\",\"162\",\"162\",\"160\",\"161\",\"161\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"160\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"163\",\"162\",\"161\",\"163\",\"162\",\"162\",\"163\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"163\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"163\",\"162\",\"163\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"160\",\"160\",\"162\",\"162\",\"163\",\"160\",\"163\",\"163\",\"162\",\"163\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"163\",\"161\",\"162\",\"163\",\"162\",\"160\",\"159\",\"160\",\"162\",\"162\",\"160\",\"161\",\"161\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"160\",\"163\",\"160\",\"162\",\"163\",\"163\",\"161\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"161\",\"163\",\"162\",\"162\",\"161\",\"161\",\"159\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"161\",\"162\",\"160\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"159\",\"161\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"159\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"159\",\"160\",\"161\",\"162\",\"161\",\"162\",\"159\",\"159\",\"162\",\"162\",\"162\",\"162\",\"159\",\"162\",\"162\",\"160\",\"162\",\"162\",\"161\",\"162\",\"161\",\"163\",\"162\",\"163\",\"162\",\"162\",\"163\",\"162\",\"163\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"161\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"158\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"161\",\"160\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"161\",\"162\",\"163\",\"159\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"163\",\"162\",\"162\",\"162\",\"163\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"163\",\"162\",\"163\",\"161\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"163\",\"162\",\"163\",\"162\",\"164\",\"162\",\"162\",\"162\",\"163\",\"164\",\"163\",\"162\",\"163\",\"163\",\"162\",\"161\",\"162\",\"161\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"163\",\"162\",\"161\",\"162\",\"164\",\"162\",\"163\",\"162\",\"163\",\"162\",\"161\",\"161\",\"163\",\"160\",\"162\",\"162\",\"162\",\"163\",\"160\",\"162\",\"162\",\"163\",\"160\",\"162\",\"162\",\"161\",\"160\",\"162\",\"162\",\"161\",\"162\",\"159\",\"162\",\"162\",\"162\",\"164\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"164\",\"162\",\"162\",\"163\",\"163\",\"162\",\"162\",\"163\",\"162\",\"162\",\"162\",\"163\",\"164\",\"163\",\"162\",\"163\",\"162\",\"164\",\"163\",\"162\",\"163\",\"164\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"161\",\"163\",\"161\",\"163\",\"162\",\"161\",\"162\",\"162\",\"162\",\"162\",\"162\",\"162\",\"160\",\"162\",\"162\",\"162\",\"162\",\"161\",\"162\",\"162\",\"162\",\"165\",\"163\",\"162\",\"161\",\"162\",\"161\",\"161\",\"165\",\"163\",\"162\"],[0.317,0.306,0.315,0.331,0.335,0.319,0.305,0.336,0.357,0.314,0.337,0.339,0.31,0.31,0.327,0.326,0.333,0.315,0.311,0.306,0.306,0.314,0.319,0.308,0.313,0.313,0.294,0.309,0.335,0.303,0.316,0.31,0.341,0.322,0.335,0.317,0.325,0.323,0.331,0.321,0.316,0.337,0.337,0.313,0.31,0.304,0.34,0.332,0.322,0.317,0.296,0.338,0.314,0.31,0.309,0.319,0.303,0.307,0.328,0.319,0.34,0.314,0.336,0.327,0.334,0.325,0.323,0.342,0.326,0.332,0.331,0.33,0.342,0.327,0.316,0.338,0.317,0.33,0.322,0.313,0.311,0.348,0.308,0.313,0.313,0.319,0.308,0.319,0.326,0.33,0.33,0.323,0.353,0.335,0.324,0.325,0.333,0.351,0.328,0.336,0.333,0.344,0.343,0.338,0.312,0.345,0.331,0.342,0.327,0.329,0.329,0.346,0.333,0.316,0.314,0.319,0.324,0.331,0.339,0.352,0.318,0.336,0.361,0.323,0.316,0.32,0.345,0.33,0.344,0.353,0.333,0.328,0.328,0.323,0.315,0.323,0.324,0.331,0.329,0.328,0.329,0.362,0.332,0.351,0.341,0.332,0.314,0.362,0.309,0.343,0.334,0.327,0.354,0.314,0.322,0.338,0.343,0.322,0.33,0.338,0.364,0.337,0.339,0.328,0.326,0.333,0.324,0.329,0.34,0.329,0.346,0.352,0.311,0.349,0.334,0.336,0.358,0.356,0.315,0.339,0.335,0.343,0.357,0.343,0.342,0.326,0.337,0.335,0.346,0.321,0.347,0.319,0.367,0.316,0.33,0.333,0.312,0.323,0.326,0.338,0.339,0.357,0.312,0.337,0.337,0.337,0.358,0.341,0.328,0.349,0.345,0.333,0.336,0.335,0.325,0.31,0.352,0.302,0.362,0.33,0.339,0.308,0.362,0.312,0.327,0.324,0.307,0.321,0.332,0.311,0.32,0.344,0.322,0.332,0.336,0.318,0.355,0.343,0.324,0.333,0.326,0.35,0.329,0.348,0.318,0.321,0.338,0.348,0.342,0.372,0.34,0.324,0.328,0.352,0.323,0.32,0.323,0.342,0.335,0.328,0.332,0.33,0.342,0.318,0.338,0.332,0.313,0.342,0.344,0.348,0.327,0.322,0.327,0.346,0.327,0.324,0.322,0.349,0.329,0.359,0.352,0.325,0.326,0.348,0.306,0.348,0.319,0.327,0.345,0.314,0.314,0.327,0.336,0.341,0.311,0.321,0.336,0.347,0.36,0.337,0.314,0.305,0.313,0.336,0.308,0.331,0.33,0.338,0.348,0.349,0.343,0.341,0.33,0.349,0.315,0.352,0.318,0.329,0.327,0.309,0.315,0.328,0.342,0.346,0.315,0.319,0.323,0.357,0.355,0.344,0.331,0.311,0.314,0.337,0.329,0.321,0.334,0.341,0.341,0.35,0.357,0.338,0.325,0.348,0.323,0.35,0.325,0.339,0.314,0.318,0.308,0.329,0.344,0.33,0.301,0.329,0.328,0.345,0.362,0.339,0.351,0.326,0.319,0.352,0.322,0.348,0.346,0.341,0.35,0.354,0.34,0.348,0.353,0.362,0.332,0.357,0.347,0.353,0.327,0.336,0.348,0.343,0.361,0.34,0.339,0.342,0.338,0.345,0.369,0.354,0.346,0.32,0.314,0.35,0.315,0.346,0.353,0.324,0.347,0.384,0.349,0.359,0.326,0.365,0.336,0.356,0.342,0.342,0.331,0.329,0.344,0.347,0.343,0.333,0.368,0.345,0.355,0.371,0.346,0.353,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[0.415,0.378,0.403,0.428,0.424,0.405,0.39,0.43,0.47,0.402,0.427,0.423,0.403,0.364,0.399,0.414,0.442,0.401,0.419,0.378,0.407,0.39,0.398,0.394,0.393,0.387,0.352,0.408,0.438,0.373,0.409,0.361,0.46,0.392,0.413,0.397,0.415,0.413,0.431,0.396,0.401,0.432,0.425,0.388,0.371,0.385,0.435,0.411,0.399,0.378,0.361,0.409,0.375,0.386,0.346,0.398,0.383,0.392,0.419,0.382,0.448,0.376,0.434,0.399,0.398,0.395,0.396,0.416,0.397,0.4,0.398,0.402,0.435,0.403,0.378,0.427,0.417,0.394,0.399,0.379,0.405,0.449,0.368,0.401,0.37,0.387,0.404,0.39,0.405,0.41,0.419,0.39,0.476,0.422,0.391,0.414,0.418,0.443,0.405,0.422,0.408,0.44,0.422,0.432,0.361,0.45,0.431,0.418,0.408,0.413,0.427,0.442,0.406,0.394,0.372,0.386,0.417,0.416,0.434,0.45,0.398,0.423,0.435,0.39,0.395,0.41,0.45,0.424,0.431,0.437,0.407,0.44,0.415,0.406,0.376,0.406,0.431,0.397,0.405,0.392,0.41,0.454,0.409,0.433,0.404,0.431,0.4,0.455,0.38,0.436,0.42,0.415,0.412,0.392,0.399,0.435,0.456,0.407,0.423,0.427,0.442,0.454,0.445,0.412,0.399,0.422,0.431,0.409,0.417,0.404,0.451,0.447,0.374,0.431,0.405,0.431,0.467,0.423,0.391,0.433,0.431,0.438,0.462,0.447,0.431,0.44,0.457,0.431,0.438,0.405,0.423,0.421,0.476,0.402,0.418,0.438,0.423,0.407,0.413,0.422,0.46,0.431,0.404,0.432,0.415,0.443,0.452,0.424,0.422,0.447,0.455,0.406,0.416,0.441,0.407,0.397,0.483,0.387,0.457,0.436,0.402,0.389,0.463,0.401,0.429,0.408,0.408,0.387,0.422,0.382,0.426,0.424,0.408,0.422,0.412,0.398,0.455,0.428,0.418,0.396,0.415,0.439,0.4,0.404,0.408,0.395,0.453,0.481,0.445,0.471,0.441,0.412,0.417,0.476,0.408,0.417,0.406,0.431,0.405,0.432,0.409,0.448,0.416,0.431,0.441,0.423,0.403,0.438,0.432,0.434,0.421,0.388,0.401,0.446,0.415,0.372,0.404,0.463,0.426,0.47,0.461,0.396,0.397,0.45,0.354,0.462,0.428,0.423,0.438,0.407,0.376,0.401,0.431,0.437,0.388,0.386,0.452,0.44,0.473,0.441,0.392,0.397,0.364,0.435,0.385,0.407,0.423,0.426,0.423,0.466,0.455,0.415,0.41,0.464,0.387,0.442,0.421,0.421,0.403,0.395,0.384,0.401,0.423,0.442,0.41,0.372,0.386,0.463,0.451,0.431,0.412,0.404,0.384,0.439,0.393,0.398,0.427,0.455,0.417,0.48,0.461,0.411,0.437,0.45,0.411,0.44,0.437,0.441,0.419,0.398,0.38,0.424,0.433,0.45,0.378,0.404,0.428,0.452,0.494,0.435,0.453,0.424,0.402,0.449,0.411,0.452,0.434,0.438,0.425,0.471,0.443,0.429,0.476,0.474,0.407,0.42,0.466,0.449,0.403,0.422,0.423,0.448,0.432,0.416,0.416,0.412,0.434,0.451,0.475,0.456,0.427,0.402,0.377,0.441,0.398,0.467,0.447,0.411,0.439,0.499,0.451,0.44,0.397,0.454,0.422,0.457,0.465,0.418,0.418,0.4,0.428,0.447,0.42,0.43,0.454,0.423,0.427,0.448,0.459,0.456,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Team<\\/th>\\n      <th>League<\\/th>\\n      <th>Year<\\/th>\\n      <th>RS<\\/th>\\n      <th>RA<\\/th>\\n      <th>W<\\/th>\\n      <th>OBP<\\/th>\\n      <th>SLG<\\/th>\\n      <th>BA<\\/th>\\n      <th>Playoffs<\\/th>\\n      <th>RankSeason<\\/th>\\n      <th>RankPlayoffs<\\/th>\\n      <th>G<\\/th>\\n      <th>OOBP<\\/th>\\n      <th>OSLG<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[3,4,5,6,7,8,9,14,15]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nHowever, the description within the [OpenML](https://cran.r-project.org/package=OpenML) object is not very detailed.\nThe previously referenced [page](https://www.openml.org/d/41021) however states the following:\n\nIn the early 2000s, Billy Beane and Paul DePodesta worked for the Oakland Athletics.\nDuring their work there, they disrupted the game of baseball.\nThey didn't do it using a bat or glove, and they certainly didn't do it by throwing money at the issue; in fact, money was the issue.\nThey didn't have enough of it, but they were still expected to keep up with teams that had more substantial endorsements.\nThis is where Statistics came riding down the hillside on a white horse to save the day.\nThis data set contains some of the information that was available to Beane and DePodesta in the early 2000s, and it can be used to better understand their methods.\n\nThis data set contains a set of variables that Beane and DePodesta emphasized in their work.\nThey determined that statistics like on-base percentage (obp) and slugging percentage (slg) were very important when it came to scoring runs, however, they were largely undervalued by most scouts at the time.\nThis translated to a gold mine for Beane and DePodesta.\nSince these players weren't being looked at by other teams, they could recruit these players on a small budget.\nThe variables are as follows:\n\n* team\n* league\n* year\n* runs scored (rs)\n* runs allowed (ra)\n* wins (w)\n* on-base percentage (obp)\n* slugging percentage (slg)\n* batting average (ba)\n* playoffs (binary)\n* rankseason\n* rankplayoffs\n* games played (g)\n* opponent on-base percentage (oobp)\n* opponent slugging percentage (oslg)\n\nWhile Beane and DePodesta defined most of these statistics and measures for individual players, this data set is on the team level.\n\nThese statistics seem very informative if you are into baseball.\nIf baseball of rather obscure to you, simply take these features as given or give this [article](https://en.wikipedia.org/wiki/Baseball_statistics) a quick read.\n\nFinally, note that the `moneyball` dataset is also included in the [mlr3data](https://mlr3data.mlr-org.com)  package where you can get the preprocessed (integers properly encoded as such, etc.) data via:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(\"moneyball\", package = \"mlr3data\")\nskimr::skim(moneyball)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |          |\n|:------------------------|:---------|\n|Name                     |moneyball |\n|Number of rows           |1232      |\n|Number of columns        |15        |\n|_______________________  |          |\n|Column type frequency:   |          |\n|factor                   |6         |\n|numeric                  |9         |\n|________________________ |          |\n|Group variables          |None      |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                           |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------------------------|\n|team          |         0|           1.0|FALSE   |       39|BAL: 47, BOS: 47, CHC: 47, CHW: 47   |\n|league        |         0|           1.0|FALSE   |        2|AL: 616, NL: 616                     |\n|playoffs      |         0|           1.0|FALSE   |        2|0: 988, 1: 244                       |\n|rankseason    |       988|           0.2|FALSE   |        8|2: 53, 1: 52, 3: 44, 4: 44           |\n|rankplayoffs  |       988|           0.2|FALSE   |        5|3: 80, 4: 68, 1: 47, 2: 47           |\n|g             |         0|           1.0|FALSE   |        8|162: 954, 161: 139, 163: 93, 160: 23 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|    sd|      p0|     p25|     p50|     p75|    p100|hist  |\n|:-------------|---------:|-------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:-----|\n|year          |         0|          1.00| 1988.96| 14.82| 1962.00| 1976.75| 1989.00| 2002.00| 2012.00|▆▆▇▆▇ |\n|rs            |         0|          1.00|  715.08| 91.53|  463.00|  652.00|  711.00|  775.00| 1009.00|▁▆▇▃▁ |\n|ra            |         0|          1.00|  715.08| 93.08|  472.00|  649.75|  709.00|  774.25| 1103.00|▂▇▆▂▁ |\n|w             |         0|          1.00|   80.90| 11.46|   40.00|   73.00|   81.00|   89.00|  116.00|▁▃▇▆▁ |\n|obp           |         0|          1.00|    0.33|  0.02|    0.28|    0.32|    0.33|    0.34|    0.37|▁▃▇▅▁ |\n|slg           |         0|          1.00|    0.40|  0.03|    0.30|    0.38|    0.40|    0.42|    0.49|▁▅▇▅▁ |\n|ba            |         0|          1.00|    0.26|  0.01|    0.21|    0.25|    0.26|    0.27|    0.29|▁▂▇▆▂ |\n|oobp          |       812|          0.34|    0.33|  0.02|    0.29|    0.32|    0.33|    0.34|    0.38|▂▇▇▃▁ |\n|oslg          |       812|          0.34|    0.42|  0.03|    0.35|    0.40|    0.42|    0.44|    0.50|▁▆▇▅▁ |\n:::\n:::\n\n\nThe summary shows how this data we are dealing with looks like:\nSome data is missing, however, this has structural reasons.\nThere are 39 teams with each maximally 47 years (1962 - 2012).\nFor 988 cases the information on `rankseason` and `rankplayoffs` is missing.\nThis is since these simply did not reach the playoffs and hence have no reported rank.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(moneyball[moneyball$playoffs == 0, c(\"rankseason\", \"rankplayoffs\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   rankseason  rankplayoffs\n 1      :  0   1   :  0    \n 2      :  0   2   :  0    \n 3      :  0   3   :  0    \n 4      :  0   4   :  0    \n 5      :  0   5   :  0    \n (Other):  0   NA's:988    \n NA's   :988               \n```\n:::\n:::\n\n\nOn the other hand, `oobp` and `oslg` have $812$ missing values.\nIt seems as if these measures were not available before $1998$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(naniar)\n\nggplot(moneyball, aes(x = year, y = oobp)) +\n  geom_miss_point()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/2020-05-04-moneyball-008-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nWe seem to have a missing data problem.\nTypically, in this case, we have three options:\nThey are:\n\n* Complete case analysis: Exclude all observation with missing values.\n\n* Complete feature analysis: Exclude all features with missing values.\n\n* Missing value imputation: Use a model to \"guess\" the missing values (based on the underlying distribution of the data.\n\nUsually, missing value imputation is preferred over the first two.\nHowever, in machine learning, one can try out all options and see which performs best for the underlying problem.\nFor now, we limit ourselves to a rather simple imputation technique, imputation by randomly sampling from the univariate distribution.\nNote that this does not take the multivariate distribution into account properly and that there are more elaborate approaches.\nWe only aim to impute `oobp` and `oslg`.\nFor the other missing (categorical) features, we simply add a new level which indicates that information is missing (i.e. all missing values belong to).\n\nIt is important to note that in this case here the vast majority of information on the features is missing.\nIn this case, imputation is performed to not throw away the existing information of the features.\n\n[mlr3](https://mlr3.mlr-org.com) has some solutions for that within the [mlr3pipelines](https://mlr3pipelines.mlr-org.com)  package.\nWe start with an easy [`PipeOp`](https://mlr3pipelines.mlr-org.com/reference/PipeOp.html) which only performs numeric imputation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nimp_num = po(\"imputehist\", affect_columns = selector_type(c(\"integer\", \"numeric\")))\n```\n:::\n\n\nNext, we append the second imputation job for factors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nimp_fct = po(\"imputeoor\", affect_columns = selector_type(\"factor\"))\ngraph = imp_num %>>% imp_fct\ngraph$plot(html = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/2020-05-04-moneyball-010-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Creating tasks and learners\n\nThe fact that there is missing data does not affect the [`task`](https://mlr3.mlr-org.com/reference/Task.html) definition.\nThe [`task`](https://mlr3.mlr-org.com/reference/Task.html) determines what is the problem to be solved by machine learning.\nWe want to explain the runs scored (`rs`).\n`rs` is an important measure as a run is equivalent to a 'point' scored in other sports.\nNaturally, the aim of a coach should be to maximise runs scored and minimise runs allowed.\nAs runs scored and runs allowed are both legitimate targets we ignore the runs allowed here.\nThe task is defined by:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# creates a `mlr3` task from scratch, from a data.frame\n# 'target' names the column in the dataset we want to learn to predict\ntask = as_task_regr(moneyball, target = \"rs\")\ntask$missings()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-e1d851c28fe18740c04d\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e1d851c28fe18740c04d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[0],[0],[0],[0],[0],[812],[812],[0],[0],[988],[988],[0],[0],[0],[0]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>rs<\\/th>\\n      <th>ba<\\/th>\\n      <th>g<\\/th>\\n      <th>league<\\/th>\\n      <th>obp<\\/th>\\n      <th>oobp<\\/th>\\n      <th>oslg<\\/th>\\n      <th>playoffs<\\/th>\\n      <th>ra<\\/th>\\n      <th>rankplayoffs<\\/th>\\n      <th>rankseason<\\/th>\\n      <th>slg<\\/th>\\n      <th>team<\\/th>\\n      <th>w<\\/th>\\n      <th>year<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nThe `$missings()` method indicates what we already knew: our missing values.\nMissing values are not always a problem.\nSome learners can deal with them pretty well.\nHowever, we want to use a random forest for our task.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# creates a learner\ntest_learner = lrn(\"regr.ranger\")\n\n# displays the properties\ntest_learner$properties\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"hotstart_backward\" \"importance\"        \"oob_error\"         \"weights\"          \n```\n:::\n:::\n\n\nTypically, in [mlr3](https://mlr3.mlr-org.com) the `$properties` field would tell us whether missing values are a problem to this learner or not.\nAs it is not listed here, the random forest cannot deal with missing values.\n\nAs we aim to use imputation beforehand, we incorporate it into the learner.\nOur selected learner is going to be a random forest from the [ranger](https://cran.r-project.org/package=ranger) package.\n\nOne can allow the embedding of the preprocessing (imputation) into a learner by creating a [`PipeOpLearner`](https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_learner.html).\nThis special [`Learner`](https://mlr3.mlr-org.com/reference/Learner.html) can be put into a graph together with the `imputer`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# convert learner to pipeop learner and set hyperparameter\npipeop_learner = po(lrn(\"regr.ranger\"), num.trees = 1000, importance = \"permutation\")\n\n# add pipeop learner to graph and create graph learner\ngraph_learner = as_learner(graph %>>% pipeop_learner)\n```\n:::\n\n\nThe final graph looks like the following:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngraph_learner$graph$plot(html = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/2020-05-04-moneyball-015-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Train and predict\n\nTo get a feeling of how our model performs we simply train the [`Learner`](https://mlr3.mlr-org.com/reference/Learner.html) on a subset of the data and predict the hold-out data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# defines the training and testing data; 95% is used for training\ntrain_set = sample(task$nrow, 0.95 * task$nrow)\ntest_set = setdiff(seq_len(task$nrow), train_set)\n\n# train learner on subset of task\ngraph_learner$train(task, row_ids = train_set)\n\n# predict using held out observations\nprediction = graph_learner$predict(task, row_ids = test_set)\n\nhead(as.data.table(prediction))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-608e07ffa5b4f43786e5\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-608e07ffa5b4f43786e5\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],[16,36,51,74,82,110],[776,654,713,681,587,759],[750.085844140342,670.985265019172,708.810777651515,661.074958124431,614.607090892094,710.515339682318]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>row_ids<\\/th>\\n      <th>truth<\\/th>\\n      <th>response<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nViewing the predicted values it seems like the model predicts reasonable values that are fairly close to the truth.\n\n## Evaluation & Resampling\n\nWhile the prediction indicated that the model is doing what it is supposed to, we want to have a more systematic understanding of the model performance.\nThat means we want to know by how much our model is away from the truth on average.\nCross-validation investigates this question.\nIn [mlr3](https://mlr3.mlr-org.com) 10-fold cross-validation is constructed as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncv10 = rsmp(\"cv\", folds = 10)\nrr = resample(task, graph_learner, cv10)\n```\n:::\n\n\nWe choose some of the performance measures provided by:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.data.table(mlr_measures)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-7fd1976dd0e152d552bc\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7fd1976dd0e152d552bc\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\"],[\"aic\",\"bic\",\"classif.acc\",\"classif.auc\",\"classif.bacc\",\"classif.bbrier\",\"classif.ce\",\"classif.costs\",\"classif.dor\",\"classif.fbeta\",\"classif.fdr\",\"classif.fn\",\"classif.fnr\",\"classif.fomr\",\"classif.fp\",\"classif.fpr\",\"classif.logloss\",\"classif.mauc_au1p\",\"classif.mauc_au1u\",\"classif.mauc_aunp\",\"classif.mauc_aunu\",\"classif.mbrier\",\"classif.mcc\",\"classif.npv\",\"classif.ppv\",\"classif.prauc\",\"classif.precision\",\"classif.recall\",\"classif.sensitivity\",\"classif.specificity\",\"classif.tn\",\"classif.tnr\",\"classif.tp\",\"classif.tpr\",\"clust.ch\",\"clust.db\",\"clust.dunn\",\"clust.silhouette\",\"clust.wss\",\"debug\",\"oob_error\",\"regr.bias\",\"regr.ktau\",\"regr.mae\",\"regr.mape\",\"regr.maxae\",\"regr.medae\",\"regr.medse\",\"regr.mse\",\"regr.msle\",\"regr.pbias\",\"regr.rae\",\"regr.rmse\",\"regr.rmsle\",\"regr.rrse\",\"regr.rse\",\"regr.rsq\",\"regr.sae\",\"regr.smape\",\"regr.srho\",\"regr.sse\",\"selected_features\",\"sim.jaccard\",\"sim.phi\",\"time_both\",\"time_predict\",\"time_train\"],[\"Akaika Information Criterion\",\"Bayesian Information Criterion\",\"Classification Accuracy\",\"Area Under the ROC Curve\",\"Balanced Accuracy\",\"Binary Brier Score\",\"Classification Error\",\"Cost-sensitive Classification\",\"Diagnostic Odds Ratio\",\"F-beta score\",\"False Discovery Rate\",\"False Negatives\",\"False Negative Rate\",\"False Omission Rate\",\"False Positives\",\"False Positive Rate\",\"Log Loss\",\"Weighted average 1 vs. 1 multiclass AUC\",\"Average 1 vs. 1 multiclass AUC\",\"Weighted average 1 vs. rest multiclass AUC\",\"Average 1 vs. rest multiclass AUC\",\"Multiclass Brier Score\",\"Matthews Correlation Coefficient\",\"Negative Predictive Value\",\"Positive Predictive Value\",\"Precision-Recall Curve\",\"Precision\",\"Recall\",\"Sensitivity\",\"Specificity\",\"True Negatives\",\"True Negative Rate\",\"True Positives\",\"True Positive Rate\",\"Calinski Harabasz\",\"Davies Bouldin\",\"Dunn\",\"Silhouette\",\"Trace W\",\"Debug Classification Measure\",\"Out-of-bag Error\",\"Bias\",\"Kendall's tau\",\"Mean Absolute Error\",\"Mean Absolute Percent Error\",\"Max Absolute Error\",\"Median Absolute Error\",\"Median Squared Error\",\"Mean Squared Error\",\"Mean Squared Log Error\",\"Percent Bias\",\"Relative Absolute Error\",\"Root Mean Squared Error\",\"Root Mean Squared Log Error\",\"Root Relative Squared Error\",\"Relative Squared Error\",\"R Squared\",\"Sum of Absolute Errors\",\"Symmetric Mean Absolute Percent Error\",\"Spearman's rho\",\"Sum of Squared Errors\",\"Absolute or Relative Frequency of Selected Features\",\"Jaccard Similarity Index\",\"Phi Coefficient Similarity\",\"Elapsed Time\",\"Elapsed Time\",\"Elapsed Time\"],[null,null,\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"classif\",\"clust\",\"clust\",\"clust\",\"clust\",\"clust\",null,null,\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",\"regr\",null,null,null,null,null,null],[[\"mlr3\"],[\"mlr3\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3cluster\",\"clusterCrit\"],[\"mlr3\",\"mlr3cluster\",\"clusterCrit\"],[\"mlr3\",\"mlr3cluster\",\"clusterCrit\"],[\"mlr3\",\"mlr3cluster\",\"clusterCrit\"],[\"mlr3\",\"mlr3cluster\",\"clusterCrit\"],[\"mlr3\"],[\"mlr3\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\",\"mlr3measures\"],[\"mlr3\"],[\"mlr3\"],[\"mlr3\"]],[\"response\",\"response\",\"response\",\"prob\",\"response\",\"prob\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"prob\",\"prob\",\"prob\",\"prob\",\"prob\",\"prob\",\"response\",\"response\",\"response\",\"prob\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"partition\",\"partition\",\"partition\",\"partition\",\"partition\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",\"response\",null,null,null],[[],[],[],[\"twoclass\"],[],[\"twoclass\"],[],[],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[],[],[],[],[],[],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[\"twoclass\"],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>key<\\/th>\\n      <th>label<\\/th>\\n      <th>task_type<\\/th>\\n      <th>packages<\\/th>\\n      <th>predict_type<\\/th>\\n      <th>task_properties<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nWe choose the [`mean absolute error`](https://mlr3.mlr-org.com/reference/mlr_measures_regr.mae.html) and the [`mean squared error`](https://mlr3.mlr-org.com/reference/mlr_measures_regr.mse.html).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr$score(msrs(c(\"regr.mae\", \"regr.mse\")))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-615909c7788d167372d1\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-615909c7788d167372d1\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"],[1,2,3,4,5,6,7,8,9,10],[\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\",\"moneyball\"],[\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\",\"imputehist.imputeoor.regr.ranger\"],[\"cv\",\"cv\",\"cv\",\"cv\",\"cv\",\"cv\",\"cv\",\"cv\",\"cv\",\"cv\"],[18.0306344314066,17.6993949471716,18.8963186633429,19.8227152911024,20.1819357482832,20.0082933275777,23.0014175508845,18.0131007000908,19.0182898293873,19.3403053830054],[559.134377339324,505.880234243757,583.938479985664,612.009056479345,663.79550852371,604.114532286426,829.643221268012,531.714793566671,578.475126154174,586.858238203429]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>iteration<\\/th>\\n      <th>task_id<\\/th>\\n      <th>learner_id<\\/th>\\n      <th>resampling_id<\\/th>\\n      <th>regr.mae<\\/th>\\n      <th>regr.mse<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,5,6]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nWe can also compute now by how much our model was on average wrong when predicting the runs scored.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrr$aggregate(msr(\"regr.mae\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nregr.mae \n19.40124 \n```\n:::\n:::\n\n\nThat seems not too bad.\nConsidering that on average approximately 715 runs per team per season have been scored.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(moneyball$rs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 715.082\n```\n:::\n:::\n\n\n## Performance boost of imputation\n\nTo assess if imputation was beneficial, we can compare our current learner with a learner which ignores the missing features.\nNormally, one would set up a benchmark for this.\nHowever, we want to keep things short in this use case.\nThus, we only set up the alternative learner (with identical hyperparameters) and compare the 10-fold cross-validated mean absolute error.\n\nAs we are mostly interested in the numeric imputation we leave the remaining graph as it is.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nimpute_oor = po(\"imputeoor\", affect_columns = selector_type(\"factor\"))\n```\n:::\n\n\nSubsequently, we create a pipeline with [`PipeOpSelect`](https://mlr3pipelines.mlr-org.com/reference/mlr_pipeops_select.html).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfeature_names = colnames(moneyball)[!sapply(moneyball, anyNA)]\nfeature_names = c(feature_names[feature_names %in% task$feature_names],\n  \"rankseason\", \"rankplayoffs\")\nselect_na = po(\"select\", selector = selector_name(feature_names))\n\ngraph_2 = impute_oor %>>% select_na\ngraph_2$plot(html = FALSE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/2020-05-04-moneyball-026-1.png){fig-align='center' width=960}\n:::\n:::\n\n\nNow we complete the learner and apply resampling as before.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngraph_learner_2 = as_learner(graph_2 %>>% pipeop_learner)\nrr_2 = resample(task, graph_learner_2, cv10)\nrr_2$aggregate(msr(\"regr.mae\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nregr.mae \n19.03637 \n```\n:::\n:::\n\n\nSurprisingly, the performance seems to be approximately the same.\nThat means that the imputed features seem not very helpful.\nWe can use the `variable.importance` of the random forest.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsort(graph_learner$model$regr.ranger$model$variable.importance, decreasing = TRUE)\n```\n:::\n\n::: {.cell .column-page layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-5b122b4a8454f57a3969\" style=\"width:100%;height:auto;\" class=\"datatables html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5b122b4a8454f57a3969\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\"],[3482.4200276471],[2538.01503345139],[894.773459238882],[701.369420297139],[511.878622259318],[258.507163550608],[117.582174060187],[116.293540456316],[109.573243831934],[27.0658593253564],[26.8446841696778],[25.8456235150912],[24.5606241702221],[3.99100427118945]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>slg<\\/th>\\n      <th>obp<\\/th>\\n      <th>ba<\\/th>\\n      <th>w<\\/th>\\n      <th>ra<\\/th>\\n      <th>year<\\/th>\\n      <th>playoffs<\\/th>\\n      <th>rankseason<\\/th>\\n      <th>rankplayoffs<\\/th>\\n      <th>oslg<\\/th>\\n      <th>oobp<\\/th>\\n      <th>league<\\/th>\\n      <th>team<\\/th>\\n      <th>g<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14]},{\"orderable\":false,\"targets\":0}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nWe see that according to this the left out `oobp` and `oslg` seem to have solely rudimentary explanatory power.\nThis may be because there were simply too many instances or because the features are themselves not very powerful.\n\n## Conclusion\n\nSo, to sum up, what we have learned:\nWe can access very cool data straight away with the [OpenML](https://cran.r-project.org/package=OpenML) package.\n(We are working on a better direct implementation into [mlr3](https://mlr3.mlr-org.com) at the moment.)\nWe can work with missing data very well in [mlr3](https://mlr3.mlr-org.com).\nNevertheless, we discovered that sometimes imputation does not lead to the intended goals.\nWe also learned how to use some [`PipeOp`](https://mlr3pipelines.mlr-org.com/reference/PipeOp.html)s from the [mlr3pipelines](https://mlr3pipelines.mlr-org.com)  package.\n\nBut most importantly, we found a way to predict the runs scored of MLB teams.\n\nIf you want to know more, read the [mlr3book](https://mlr3book.mlr-org.com/) and the documentation of the mentioned packages.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\n<link href=\"../../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/datatables-binding-0.25/datatables.js\"></script>\n<script src=\"../../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../../site_libs/dt-core-1.11.3/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../../site_libs/dt-core-1.11.3/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/dt-core-1.11.3/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}