---
title: "OpenML tutorial at useR!2017 Brussels"
authors: ["Giuseppe Casalicchio"]
date: 2017-03-02
categories: ["R", "r-bloggers"]
tags: ["OpenML", "tutorial", "useR"]

description: "Announcing an OpenML presentation at useR"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## What is OpenML?

Conducting research openly and reproducibly is becoming the gold standard in academic research. Practicing open and reproducible research, however, is hard. [OpenML.org](https://www.openml.org) (Open Machine Learning) is an online platform that aims at making the part of research involving data and analyses easier. It automatically connects data sets, research tasks, algorithms, analyses and results and allows users to access all components including meta information through a REST API in a machine readable and standardized format. Everyone can see, work with and expand other people’s work in a fully reproducible way.

## The useR Tutorial

At [useR!2017](https://user2017.brussels/), we will we will present an [R package](https://github.com/openml/r) to interface the OpenML platform and illustrate its usage both as a stand-alone package and in combination with the [mlr](https://github.com/mlr-org/mlr) machine learning package. Furthermore, we show how the OpenML package allows R users to easily search, download and upload machine learning datasets.

