---
title: "Feature Selection Filter"
description: |
  Feature Selection Filters.
preview: images/logo_color.png
site: distill::distill_website
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
library(mlr3filters)

content = as.data.table(mlr_filters, objects = TRUE)[, .(key, label, task_type, packages)]

# add links
content[, key := link_keys(key, prefix = "mlr_filters")]
content[, packages := link_pkgs(packages, remove = "mlr3filters")]
content[, task_type := map(task_type, strsplit, split = ",", fixed = TRUE)]

# add line breaks to cells
cols = c("packages", "task_type")
content[, (cols) := map(.SD, function(col) map_chr(col, function(x) paste0(x, collapse = "<br/>"))), .SDcols = cols]


setnames(content, c("Key", "Task Types", "Packages"))
```

```{r, layout="l-body-outset"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames= FALSE)
```
