---
title: "Graphs"
description: |
  Graphs of the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
library(mlr3pipelines)
library(mlr3proba)

content = rowwise_table(
  ~ key, ~label,
  "bagging", "Bagging Learner",
  "greplicate", "Disjoint Graph Union of Copies of a Graph",
  "ovr", "'One vs. Rest' Classification",
  "robustify", "Robustify a Learner",
  "stacking", "Stacking",
  "targettrafo", "Transform and Re-Transform the Target Variable",
  "survaverager", "Survival Prediction Averaging",
  "survbagging", "Survival Prediction Bagging",
  "survtoregr", "Survival to Regression Reduction"
)

# add links
content[, key := link_keys(key, prefix = "mlr_graphs")]

# link_keys fails
# mlr_graphs_branching is renamed to mlr_graphs_branch
# remove when label branch is merged to master
content = rbindlist(list(content, list(key = "branch", label = "Branch Between Alternative Paths")))

setnames(content, c("Key", "Label"))
```

Graphs are predefined arrangements of `r ref("PipeOp")` objects from the `r mlr_pkg("mlr3pipelines")` package.
The goal is to simplify some popular operations which usually consist of multiple steps.


```{r, layout="l-body-outset"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames = FALSE)
```
