---
title: "Machine Learning in R"
description: |
  An open-source machine learning framework providing a unified interface for machine learning in the R language.
preview: images/logo_color.png
site: distill::distill_website
output:
    distill::distill_article:
      includes:
        before_body: _banner.html
---

```{r, echo = FALSE}
# Feature grid
library(mlr3misc)
library(htmltools)
library(data.table)

content = rowwise_table(
    ~icon,          ~text,                                                    ~link,
    "code-square",  "A scientifically designed and easy to learn interface.", "index.html",
    "pen",          "More than 100 connected machine learning algorithms.",   "learners.html",
    "box",          "Light on dependencies.",                                 "index.html",
    "stack",        "Convenient parallelization with the future package.",    "https://futureverse.org/",
    "sliders",      "State-of-the-art optimization algorithms.",              "tuners.html",
    "share",        "Dataflow programming with pipelines.",                   "https://mlr3pipelines.mlr-org.com/"
)

div(class = "grid-container-feature",
  pmap(content, function(icon, text, link) {
    div(class = "grid-item-feature",
        div(class="grid-icon-feature",
          a(href = link,
            tags$i(class = sprintf("bi-%s", icon))
         )
       ),
      text
    )
  })
)
```

```{r, echo = FALSE}
# Social buttons
content = rbindlist(list(
  list(name = "GitHub", url = "https://github.com/mlr-org/mlr3", icon = "github"),
  list(name = "Mattermost", url = "https://lmmisld-lmu-stats-slds.srv.mwn.de/mlr_invite/", icon = "chat-dots"),
  list(name = "Book", url = "https://mlr3book.mlr-org.com/", icon = "book"),
  list(name = "StackOverflow", url = "https://stackoverflow.com/questions/tagged/mlr3", icon = "stack-overflow")
))

div(class = "btn-container",
  pmap(content, function(name, url, icon) {
    a(href = url, class="btn",
      tags$i(class = sprintf("bi-%s", icon)),
      name
    )
  })
)
```

## Quick Start

The mlr3verse meta-package installs mlr3 and some of the most important extension packages:

```{r, eval=FALSE}
install.packages("mlr3verse")
```

## Examples

```{r, echo = FALSE}
library(mlr3misc)
library(htmltools)
library(data.table)

example_grid = function(content) {
  div(class = "grid-container-example",
    pmap(content, function(name, icon, url, text, objective) {
        div(class = "grid-item-example",
          h3(
            tags$i(class = sprintf("bi-%s", icon)),
            HTML("&nbsp;"),
            name
          ),
          paste0(text, "."),
          a(href = url, span(class = "grid-link-example")),
          tags$ul(
            map(objective, function(x) tags$li(x))
          )
        )
    })
  )
}


content = rowwise_table(
  ~name,                    ~icon,      ~url,                                                                                  ~text,                                                          ~objective,
  "Basic Machine Learning", "pen",      "gallery/2020-03-18-iris-mlr3-basics/index.html",                                      "Basic machine learning on the Pima Indians Diabetes data set", list(list("Learner", "Task", "Resampling")),
  "Hyperparameter Tuning",  "sliders",  "gallery/2022-03-08-hyperparameter-tuning-on-the-palmer-penguins-data-set/index.html", "Hyperparameter tuning on the Palmer Penguins data set",        list(list("Tuning space", "Transformations", "Tuning"))
)

example_grid(content)
```

## Citing mlr3

If you use `mlr3`, please cite our JOSS article:

<div class="citation">
```
@Article{mlr3,
  title = {{mlr3}: A modern object-oriented machine learning framework in {R}},
  author = {Michel Lang and Martin Binder and Jakob Richter and Patrick Schratz and Florian Pfisterer and Stefan Coors and Quay Au and Giuseppe Casalicchio and Lars Kotthoff and Bernd Bischl},
  journal = {Journal of Open Source Software},
  year = {2019},
  month = {dec},
  doi = {10.21105/joss.01903},
  url = {https://joss.theoj.org/papers/10.21105/joss.01903},
}
```
</div>
