---
title: "Learners"
description: |
  Learners of the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
```

```{r}
library(mlr3)
library(mlr3learners)
library(mlr3extralearners)

content = as.data.table(mlr_learners, objects = TRUE)
content[, base_package := map(object, function(x) strsplit(x$man, "::", TRUE)[[1]][1])]
content[, packages := pmap(list(packages, base_package), function(x, y) setdiff(x, c(y, "mlr3")))]

# add links
content[, key := pmap_chr(list(base_package, key), function(base_package, key) as.character(a(href = sprintf("https://%s.mlr-org.com/reference/mlr_learners_%s.html", base_package, key), key)))]
content[, packages := link_pkgs(packages)]

# add line breaks to cells
sdcols = c("packages", "properties", "feature_types", "predict_types")
content[, (sdcols) := map(.SD, function(col) map_chr(col, function(x) paste0(x, collapse = "<br/>"))), .SDcols = sdcols]

setcolorder(content, c("label", "key", "base_package", "packages", "feature_types", "predict_types", "properties"))
content[, `:=`(object = NULL, task_type = NULL)]
colnames = col.names = c("Name", "ID", "Base Package", "Packages", "Feature Types", "Predict Types", "Properties")
```

```{r, layout="l-page"}
datatable(
  content,
  style = "bootstrap",
  colnames = colnames,
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames= FALSE)
```
