---
title: "Measures"
description: |
  Performance Measures of the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
requireNamespace("mlr3verse")

content = as.data.table(mlr3::mlr_measures)[, .(key, label, task_type, packages)]
content[, key := link_keys(key, prefix = "mlr_measures")]
content[, packages := link_pkgs(packages, remove = c("mlr3", "mlr3measures"))]
content[is.na(task_type), task_type := "generic"]

setnames(content, c("Key", "Label", "Task Type", "Packages"))
tabs = split(content, content[["Task Type"]], keep.by = FALSE)
```

Measures operate on `r ref("Prediction")` objects generated by learners.
They quantify the prediction by comparing prediction with ground truth.
The `r ref("Measure")` objects provide an abstraction for a plethora of performance measures.

```{r, layout="l-page"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames = FALSE)
```
