---
sidebar: false
toc: false
---

{{< include _setup.qmd >}}

```{r}
#| include: false

requireNamespace("mlr3verse")
```

# Measures

Measures operate on `r ref("Prediction")` objects generated by learners.
They quantify the prediction by comparing prediction with ground truth.
The `r ref("Measure")` objects provide an abstraction for a plethora of performance measures.

```{r}
#| echo: false
#| column: page

content = as.data.table(mlr3::mlr_measures)[, .(key, label, task_type, packages)]
content[is.na(task_type), task_type := "generic"]

reactable(content, columns = list(
  key = colDef(
    cell = function(value) {
      mlr3book::ref(sprintf("%s_%s", "mlr_measures", value), text = value, format = "htmltools")
    }
  ),
  label = colDef(name = "Label"),
  packages = colDef(name = "Packages", cell = function(value) {
    value = setdiff(value, c("mlr3", "mlr3measures"))
    if (length(value)) {
      tags$ul(map(value, function(x) tags$li(class = "object-table__list", mlr3book::ref_pkg(x, pkg = x, format = "htmltools"))))
    }
  }),
  task_type = colDef(name = "Task Type")
  ),
  searchable = TRUE,
  pagination = FALSE
)
```
