---
sidebar: false
toc: false
---

# Pipeline Operators

{{< include _setup.qmd >}}

```{r}
#| include: false

library("mlr3verse")
library("mlr3proba")
library("mlr3fda")
library("mlr3torch")
```

Objects of class `r ref("PipeOp")` are the building blocks to compose linear machine learning pipelines and non-linear `r ref("Graph", text = "Graphs")`.
The base objects are implemented in `r ref_pkg("mlr3pipelines")`.

```{r}
#| echo: false
#| column: page

content = as.data.table(mlr_pipeops, objects = TRUE)[, .(key, label, packages, tags)]
content = content[key %nin% c(
  "crankcompose",
  "distrcompose",
  "breslowcompose",
  "fda.cor",
  "fda.extract",
  "fda.flatten",
  "fda.fpca",
  "fda.interpol",
  "fda.scalerange",
  "fda.smooth")] # deprecated, no help page
content[, packages := map(packages, function(value) setdiff(value, "mlr3pipelines"))]
content = content[, .(key, label, packages, tags)]

ref_cell = function(value) {
  if (!length(value)) return(NULL)
  mlr3website::ref(sprintf("%s_%s", "mlr_pipeops", value), text = value, format = "htmltools")
}

reactable(content, columns = list(
    key = colDef(name = "Key", cell = ref_cell),
    label = colDef(name = "Label"),
    packages = colDef(name = "Packages", cell = package_list_cell),
    tags = colDef(name = "Tags", cell = list_cell)
  ),
  searchable = TRUE,
  pagination = FALSE,
  highlight = TRUE
)
```
