---
title: "Resources"
description: |
  Useful resources for learning mlr3
preview: images/logo_color.png
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include = FALSE}
# Collection of resources
# Resources are rendered in a 3 columns grid.
# Text description should be one sentence

library(mlr3misc)
library(htmltools)
library(data.table)

resource_grid = function(content) {
  div(class = "grid-container-package",
    pmap(content, function(category, name, icon, url, text) {
        div(class = "grid-item-package",
          h3(
            a(href = url, name),
            tags$i(class = sprintf("bi-%s", icon))
          ),
          paste0(text, ".")
        )
    })
  )
}

content = rowwise_table(
    ~category,    ~name,               ~icon,       ~url,                                                    ~text,
    "general",    "Book",              "book",      "https://mlr3book.mlr-org.com/",                         "Central entry point to the mlr3verse",
    "general",    "Gallery",           "image",     "https://mlr3gallery.mlr-org.com/",                      "The gallery has some case studies and demonstrates how frequently occurring problems can be solved",

    "article",    "mlr3",              "file-text", "https://doi.org/10.21105/joss.01903",                   "A modern object-oriented machine learning framework in R (2019). Journal of Open Source Software 4(44), 1903",
    "article",    "mlr3proba",         "file-text", "https://doi.org/10.1093/bioinformatics/btab039",        "An R Package for Machine Learning in Survival Analysis (2021). Bioinformatics, Volume 37, Issue 17, Pages 2789-2791",
    "article",    "mlr3pipelines",     "file-text", "https://jmlr.org/papers/v22/21-0281.html",              "Journal of Machine Learning Research (2021). Journal of Machine Learning Research 22(184):1-7",

    "cheatsheet", "mlr3",              "file-text", "https://cheatsheets.mlr-org.com/mlr3.pdf",              "Core package cheat sheet",
    "cheatsheet", "mlr3tuning",        "file-text", "https://cheatsheets.mlr-org.com/mlr3tuning.pdf",        "Tuning cheat sheet",
    "cheatsheet", "mlr3fselect",       "file-text", "https://cheatsheets.mlr-org.com/mlr3fselect.pdf",       "Feature selection cheat sheet",
    "cheatsheet", "mlr3pipelines",     "file-text", "https://cheatsheets.mlr-org.com/mlr3pipelines.pdf",     "Pipelines cheat sheet",

    "video",      "useR2019 talk",     "youtube",   "https://www.youtube.com/watch?v=wsP2hiFnDQs",           "on mlr3book",
    "video",      "useR2019 talk",     "youtube",   "https://www.youtube.com/watch?v=gEW5RxkbQuQ",           "on mlr3pipelines and mlr3tuning",
    "video",      "useR2020 tutorial", "youtube",   "https://www.youtube.com/watch?v=T43hO2o_nZw",           "on mlr3, mlr3tuning and mlr3pipelines",
    "video",      "ODSC talk 2021",    "youtube",   "https://av.tib.eu/media/55271",                         "on mlr3spatiotempcv and mlr3spatial",

    "course",     "I2ML course",       "display",   "https://introduction-to-machine-learning.netlify.app/", "on mlr3book",
    "course",     "mlr-outreach",      "display",   "https://github.com/mlr-org/mlr-outreach",               "on mlr3pipelines and mlr3tuning"
)

setkeyv(content, "category")
```

## General

```{r, echo = FALSE}
resource_grid(content[.("general")])
```

## Peer-reviewed Articles

```{r, echo = FALSE}
resource_grid(content[.("article")])
```

## Cheat Sheets

```{r, echo = FALSE}
resource_grid(content[.("cheatsheet")])
```

## Videos

```{r, echo = FALSE}
resource_grid(content[.("video")])
```

## Courses/Lectures

```{r, echo = FALSE}
resource_grid(content[.("course")])
```
