---
title: "Tasks"
description: |
  Tasks shipped with the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
requireNamespace("mlr3verse")

content = as.data.table(mlr3::mlr_tasks)[, .(key, label, task_type, nrow, ncol)]
content[, key := link_keys(key, prefix = "mlr_tasks")]
setnames(content, c("Key", "Label", "Task Type", "# rows", "# cols"))
```

The mlr3 packages also ship with some data sets, readily usable as `r ref("Task")` objects.
The goal of these tasks is to quickly demonstrate the capabilities of the packages.

## Table

```{r, layout="l-page"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames= FALSE)
```

## Example Usage

Create a classification task from the data set in the `r cran_pkg("palmerpenguins")` package.

```{r, echo = TRUE}
library("mlr3verse")

data("penguins", package = "palmerpenguins")

# create a task
task = as_task_classif(penguins, target = "species")
task

# get the dimensions
c(task$nrow, task$ncol)

# check for missing values
task$missings()

# plot class frequencies
autoplot(task)
```
