---
sidebar: false
toc: false
---

# Tasks

{{< include _setup.qmd >}}

```{r}
#| include: false

library("mlr3spatiotempcv")
requireNamespace("mlr3verse")
lgr::get_logger("mlr3")$set_threshold("warn")
```

The mlr3 packages also ship with some data sets, readily usable as `r ref("Task")` objects.
The goal of these tasks is to quickly demonstrate the capabilities of the packages.

```{r}
#| echo: false
#| column: page

content = as.data.table(mlr3::mlr_tasks)[, .(key, label, task_type, nrow, ncol)]

ref_cell = function(value) {
  if (!length(value)) return(NULL)
  mlr3book::ref(sprintf("%s_%s", "mlr_tasks", value), text = value, format = "htmltools")
}

reactable(content, columns = list(
    key = colDef(name = "Key", cell = ref_cell),
    label = colDef(name = "Label", minWidth = 200),
    task_type = colDef(name = "Task Type"),
    nrow = colDef(name = "# Rows"),
    ncol = colDef(name = "# Cols")
  ),
  searchable = TRUE,
  pagination = FALSE,
  highlight = TRUE
)
```

## Example Usage

Create a classification task from the data set in the `r ref_pkg("palmerpenguins")` package.

```{r}
library("mlr3verse")

# create a task
task = tsk("breast_cancer")
task

# get the dimensions
c(task$nrow, task$ncol)

# check for missing values
task$missings()

# plot class frequencies
autoplot(task)
```
