---
title: "Terminators"
description: |
  Terminators of the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
library(bbotk)

content = as.data.table(mlr_terminators)

# add line breaks to cells
sdcols = "properties"
content[, (sdcols) := map(.SD, function(col) map_chr(col, function(x) paste0(x, collapse = "<br/>"))), .SDcols = sdcols]

# add link to name and package
content[, key := map_chr(key, function(key) as.character(a(href = sprintf("https://bbotk.mlr-org.com/reference/mlr_terminators_%s.html", key), key)))]

setcolorder(content, c("key", "label", "properties", "unit"))
setnames(content,
  c("key", "label", "properties", "unit"),
  c("Key", "Name", "Properties", "Unit"))
```

```{r, layout="l-page"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames= FALSE)
```
