---
title: "Tuners"
description: |
  Tuners of the mlr3 ecosystem.
preview: images/logo_color.png
site: distill::distill_website
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mlr3website)
library(htmltools)
library(mlr3misc)
library(data.table)
library(DT)
library(mlr3tuning)
library(mlr3hyperband)
library(mlr3mbo)

content = as.data.table(mlr_tuners, objects = TRUE)
content[, base_package := map(object, function(x) strsplit(x$man, "::", TRUE)[[1]][1])]
content[, packages := pmap(list(packages, base_package), function(x, y) setdiff(x, c(y, "bbotk", "mlr3tuning")))]
content[, properties := map(properties, function(x) setdiff(x, "dependencies"))]

# add line breaks to cells
sdcols = c("param_classes", "properties", "packages")
content[, (sdcols) := map(.SD, function(col) map_chr(col, function(x) paste0(x, collapse = "<br/>"))), .SDcols = sdcols]

# add link to name and package
content[, key := pmap_chr(list(key, base_package), function(key, base_package) as.character(a(href = sprintf("https://%s.mlr-org.com/reference/mlr_tuners_%s.html", base_package, key), key)))]

setcolorder(content, c("key", "label", "base_package", "packages", "properties", "param_classes"))

content[, object := NULL]
setnames(content,
  c("label", "key", "base_package", "packages", "properties", "param_classes"),
  c("Label", "Key", "Base Package", "Packages", "Properties", "Classes"))
```

```{r, layout="l-page"}
datatable(
  content,
  style = "bootstrap",
  escape = FALSE,
  options = list(paging = FALSE, scrollY = "60vh", scrollX = TRUE, info = FALSE),
  rownames= FALSE)
```
