on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mlr-org/_gallery/<%= post_directory %>/**'
  pull_request:
    branches:
      - main
    paths:
      - 'mlr-org/_gallery/<%= post_directory %>/**'

name: mlr3website

jobs:
  render-gallery-<%= post_directory %>:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render post
        run: |
          file = file.path("mlr-org", "_gallery", "<%= post_directory %>", paste0("<%= post_file %>", ".Rmd"))
          rmarkdown::render(file, encoding = "UTF-8", params = list(eval_all = FALSE))
        shell: Rscript {0}
