---
title: "Webinar on mlr3pipelines"
authors: ["Jakob Richter"]
date: '2020-05-20'
slug: mlr3pipelines webinar
categories:
  - R
  - r-bloggers
tags:
  - mlr3
  - mlr3pipelines
output:
  distill::distill_article:
    self_contained: false
description: "Announcing the WhyR Webinar on mlr3pipelines"
---

We are happy to be invited to the [WhyR Webinar Series](http://whyr.pl/foundation/webinars/) to present you with some insights into [`mlr3pipelines`](https://mlr3pipelines.mlr-org.com/). 

The authors of `mlr3pipelines`, [Bernd Bischl](https://www.compstat.statistik.uni-muenchen.de/people/bischl/), [Martin Binder](https://www.compstat.statistik.uni-muenchen.de/people/binder/) and [Florian Pfisterer](https://www.compstat.statistik.uni-muenchen.de/people/pfisterer/) will give you a detailed overview of the vast capabilities of `mlr3pipelines`, which includes basic data preprocessing operations (like PCA, filtering etc.) but also advanced learner operations, that enable you to build you own stacked learners or ensembles.
Combined with tuning methods from [`mlr3tuning`](https://mlr3pipelines.mlr-org.com/) you can build tunable pipelines which effectively gives you the ability to construct AutoML-pipelines. 

The webinar will be live on the 28th May at 20:00 (CEST / CST+2) on [YouTube](https://www.youtube.com/embed/4r8K3GO5wk4).

Make sure to [add this event to your calendar](http://www.google.com/calendar/event?action=TEMPLATE&dates=20200528T200000Z%2F20200528T220000Z&text=mlr3pipelines%20Webinar&location=&details=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4r8K3GO5wk4) or set the reminder on YouTube. 

<iframe width="800" height="450" src="https://www.youtube.com/embed/4r8K3GO5wk4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



We will update this post once the slides are available.