on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 2"

name: gallery-weekly

jobs:
  gallery-weekly:
    runs-on: ubuntu-latest
    container: mlrorg/mlr3-website:latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Render gallery
        run: |
          cd mlr-org
          quarto render gallery
