on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 2"
  pull_request:
    paths:
      - "mlr-org/gallery/**"

name: gallery-weekly

jobs:
  gallery-weekly:
    runs-on: ubuntu-latest
    container: mlrorg/mlr3-gallery:latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install mlr3website
        run: R CMD INSTALL .

      - name: Render gallery
        run: |
          cd mlr-org
          quarto render gallery
