on:
  workflow_dispatch:
  push:
    branches:
      - gh-actions
    paths:
      - 'mlr-org/_gallery/2019-11-15-jornadas-de-usarios-de-r/**'
  pull_request:
    branches:
      - gh-actions
    paths:
      - 'mlr-org/_gallery/2019-11-15-jornadas-de-usarios-de-r/**'

name: mlr3website

jobs:
  render-gallery-2019-11-15-jornadas-de-usarios-de-r:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render post
        run: |
          file = file.path("mlr-org", "_gallery", "2019-11-15-jornadas-de-usarios-de-r", "2019-11-15-jornadas-de-usarios-de-r")
          rmarkdown::render(file, encoding = "UTF-8", params = list(eval_all = FALSE)))
        shell: Rscript {0}
